defmodule Stacks.FactoryProtoValidationTest do
  @moduledoc """
  Validates that test factories produce structs covering all proto-defined
  schema fields. Catches two forms of drift:

  1. **Field drift**: a proto field is added to a schema but the factory
     doesn't set it → the per-factory test fails.
  2. **Schema drift**: a new proto-generated schema is added but no factory
     exists → the "all proto schemas have factories" test fails.

  Only checks fields that are:
  - Defined in the Ecto schema (i.e., proto-generated)
  - Not associations (belongs_to/has_many — handled by ExMachina)
  - Not autogenerated (:id, timestamps)
  - Not virtual fields (excluded by __schema__(:fields))

  A field "covered" means the factory sets it to a non-nil value.
  Fields with schema defaults (e.g., `status: "pending"`) pass even
  if the factory doesn't explicitly set them, since the struct will
  have the default value.
  """

  use ExUnit.Case, async: true

  alias Stacks.Factory

  # Map of factory name → {schema module, optional nil fields}
  # Skip fields must actually exist in the schema — phantom entries are caught.
  @factories %{
    user:
      {Stacks.Accounts.User,
       ~w(age_verified_at age_verification_provider city website_url consent_analytics_at email_confirmation_token password_reset_token password_reset_sent_at onboarding_completed)a},
    author: {Stacks.Books.Author, ~w(website_url rss_feed_url open_library_id)a},
    book: {Stacks.Books.Book, ~w()a},
    book_edition:
      {Stacks.Books.BookEdition, ~w(cover_image_url open_library_id google_books_id)a},
    uploaded_image: {Stacks.Books.UploadedImage, ~w(storage_path rejection_reason book_ids)a},
    bookshelf: {Stacks.Shelving.Bookshelf, ~w(visibility_group_id)a},
    placement:
      {Stacks.Shelving.Placement,
       ~w(removed_at personal_rating notes listing_mode listing_status listing_price_cents listing_min_price_cents current_page started_at finished_at)a},
    placement_history: {Stacks.Shelving.PlacementHistory, ~w()a},
    post: {Stacks.Blog.Post, ~w(published_at visibility_group_id)a},
    post_comment: {Stacks.Blog.PostComment, ~w(parent_id created_at)a},
    post_book_association: {Stacks.Blog.PostBookAssociation, ~w()a},
    platform_cost: {Stacks.Costs.PlatformCost, ~w()a},
    group: {Stacks.Social.Group, ~w()a},
    group_member: {Stacks.Social.GroupMember, ~w(joined_at)a},
    group_invitation: {Stacks.Social.GroupInvitation, ~w(responded_at)a},
    visibility_grant: {Stacks.Social.VisibilityGrant, ~w()a},
    user_block: {Stacks.Social.UserBlock, ~w()a},
    listing:
      {Stacks.Marketplace.Listing, ~w(contact_info photo_urls listed_at expires_at sold_at)a},
    offer_thread: {Stacks.Marketplace.OfferThread, ~w()a},
    offer_message: {Stacks.Marketplace.OfferMessage, ~w(amount_cents)a},
    transaction:
      {Stacks.Marketplace.Transaction,
       ~w(offer_id shipping_provider_ref shipping_status shipping_cost_cents completed_at)a},
    source_health_check:
      {Stacks.Monitoring.SourceHealthCheck,
       ~w(last_success_at last_failure_at last_failure_reason)a},
    discovered_source:
      {Stacks.Enrichment.DiscoveredSource,
       ~w(confidence approved_at excluded_at exclusion_email config_generated)a},
    review_snapshot: {Stacks.Enrichment.ReviewSnapshot, ~w()a},
    bookstore: {Stacks.Enrichment.Bookstore, ~w(search_template)a},
    price_snapshot: {Stacks.Enrichment.PriceSnapshot, ~w()a},
    bookstore_event: {Stacks.Enrichment.BookstoreEvent, ~w()a},
    third_space:
      {Stacks.Enrichment.ThirdSpace,
       ~w(instagram_url description discovered_via last_active_at opted_out_at)a},
    third_space_event: {Stacks.Enrichment.ThirdSpaceEvent, ~w(recurrence)a},
    partner:
      {Stacks.Partners.Partner,
       ~w(api_key_prefix hmac_secret approved_by_id approved_at website_url third_space_id)a},
    partner_inventory_item: {Stacks.Partners.InventoryItem, ~w()a}
  }

  # Schemas that are proto-generated but intentionally have no factory.
  # EventLog: insert-only via Stacks.Events.emit/1, not ExMachina.
  # Entry: insert-only via Stacks.Audit.log/1, not ExMachina.
  @excluded_schemas [Stacks.Events.EventLog, Stacks.Audit.Entry]

  # ── Per-factory field coverage tests ──────────────────────────────────────

  for {factory_name, {schema_module, skip_fields}} <- @factories do
    @factory_name factory_name
    @schema_module schema_module
    @skip_fields skip_fields

    test "factory :#{factory_name} covers all #{inspect(schema_module)} schema fields" do
      struct = Factory.build(@factory_name)
      all_fields = @schema_module.__schema__(:fields)

      # Validate skip list: every entry must be an actual schema field.
      invalid_skips = @skip_fields -- all_fields

      assert invalid_skips == [],
             "Skip list for :#{@factory_name} contains non-existent fields: #{inspect(invalid_skips)}"

      # FK fields from belongs_to associations — set by ExMachina via build(:assoc).
      assoc_fk_fields =
        @schema_module.__schema__(:associations)
        |> Enum.map(&@schema_module.__schema__(:association, &1))
        |> Enum.filter(&match?(%Ecto.Association.BelongsTo{}, &1))
        |> Enum.map(& &1.owner_key)

      excluded =
        MapSet.new(
          [:id, :created_at, :updated_at, :inserted_at] ++ assoc_fk_fields ++ @skip_fields
        )

      testable_fields = Enum.reject(all_fields, &MapSet.member?(excluded, &1))

      missing =
        Enum.filter(testable_fields, fn field ->
          Map.get(struct, field) == nil
        end)

      assert missing == [],
             "Factory :#{@factory_name} does not set these #{inspect(@schema_module)} fields: #{inspect(missing)}. " <>
               "Either add them to the factory or to the skip list if they're legitimately optional."
    end
  end

  # ── Schema discovery: every proto-generated schema has a factory ──────────

  test "all proto-generated schemas have a factory or are explicitly excluded" do
    # All schema modules referenced by factories + excluded list
    covered =
      MapSet.new(Enum.map(@factories, fn {_, {mod, _}} -> mod end) ++ @excluded_schemas)

    # Load the manifest to get all proto-generated schema modules
    manifest_path = Path.expand("../../../../proto/persisted.exs", __DIR__)
    {manifest, _} = Code.eval_file(manifest_path)

    all_proto_modules = Enum.map(manifest.tables, & &1.ecto_module)
    uncovered = Enum.reject(all_proto_modules, &MapSet.member?(covered, &1))

    assert uncovered == [],
           "These proto-generated schemas have no factory and are not in @excluded_schemas: #{inspect(uncovered)}. " <>
             "Add a factory or add to @excluded_schemas with a comment explaining why."
  end
end
