apiVersion: 1
datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: prometheus
    access: proxy
    url: ${STACKS_VM_URL}
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST
