# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Regenerate: mix proto.sync
defmodule StacksWeb.ProtoJSON.Gen do
  @moduledoc "Proto-generated base serializers. Use StacksWeb.ProtoJSON for the public API."

  @doc "Base serializer for Book. Returns a map with all proto fields."
  def book(nil), do: nil

  def book(%Ecto.Association.NotLoaded{}), do: nil

  def book(struct) do
    %{
      id: struct.id,
      title: struct.title,
      author_id: struct.author_id,
      description: struct.description,
      subjects: struct.subjects,
      visibility_tier: struct.visibility_tier,
      language: struct.language,
      bisac_codes: struct.bisac_codes,
      created_at: format_datetime(struct.created_at),
      updated_at: format_datetime(struct.updated_at)
    }
  end

  @doc "Base serializer for Author. Returns a map with all proto fields."
  def author(nil), do: nil

  def author(%Ecto.Association.NotLoaded{}), do: nil

  def author(struct) do
    %{
      id: struct.id,
      name: struct.name,
      website: struct.website_url,
      rss_feed_url: struct.rss_feed_url,
      bio: struct.bio,
      open_library_id: struct.open_library_id,
      created_at: format_datetime(struct.created_at),
      updated_at: format_datetime(struct.updated_at)
    }
  end

  @doc "Base serializer for Edition. Returns a map with all proto fields."
  def edition(nil), do: nil

  def edition(%Ecto.Association.NotLoaded{}), do: nil

  def edition(struct) do
    %{
      id: struct.id,
      isbn: struct.isbn,
      is_primary: struct.is_primary,
      cover_image_url: struct.cover_image_url,
      page_count: struct.page_count,
      publisher: struct.publisher,
      publication_year: struct.publication_year,
      format_label: struct.format_label,
      open_library_id: struct.open_library_id,
      google_books_id: struct.google_books_id,
      created_at: format_datetime(struct.created_at),
      updated_at: format_datetime(struct.updated_at)
    }
  end

  @doc "Base serializer for User. Returns a map with all proto fields."
  def user(nil), do: nil

  def user(%Ecto.Association.NotLoaded{}), do: nil

  def user(struct) do
    %{
      id: struct.id,
      email: struct.email,
      display_name: struct.display_name,
      role: struct.role,
      country_code: struct.country_code,
      city: struct.city,
      consent_analytics: struct.consent_analytics,
      age_verified: struct.age_verified,
      profile_visibility: struct.profile_visibility,
      website_url: struct.website_url,
      consent_analytics_at: format_datetime(struct.consent_analytics_at),
      onboarding_completed: struct.onboarding_completed,
      notify_wishlist_availability: struct.notify_wishlist_availability,
      notify_marketplace: struct.notify_marketplace,
      notify_group_invitations: struct.notify_group_invitations,
      notify_event_matches: struct.notify_event_matches,
      email_confirmed: struct.email_confirmed,
      created_at: format_datetime(struct.created_at),
      updated_at: format_datetime(struct.updated_at),
      age_verified_at: format_datetime(struct.age_verified_at),
      age_verification_provider: struct.age_verification_provider
    }
  end

  @doc "Base serializer for Placement. Returns a map with all proto fields."
  def placement(nil), do: nil

  def placement(%Ecto.Association.NotLoaded{}), do: nil

  def placement(struct) do
    %{
      id: struct.id,
      book_id: struct.book_id,
      bookshelf_id: struct.bookshelf_id,
      position: struct.position,
      placed_at: format_datetime(struct.placed_at),
      removed_at: format_datetime(struct.removed_at),
      formats: struct.formats,
      personal_rating: struct.personal_rating,
      notes: struct.notes,
      visibility: struct.visibility,
      listing_mode: struct.listing_mode,
      listing_status: struct.listing_status,
      listing_price_cents: struct.listing_price_cents,
      listing_min_price_cents: struct.listing_min_price_cents,
      created_at: format_datetime(struct.created_at),
      updated_at: format_datetime(struct.updated_at)
    }
  end

  @doc "Base serializer for BlogPost. Returns a map with all proto fields."
  def blog_post(nil), do: nil

  def blog_post(%Ecto.Association.NotLoaded{}), do: nil

  def blog_post(struct) do
    %{
      id: struct.id,
      title: struct.title,
      body: struct.body,
      visibility: struct.visibility,
      user_id: struct.user_id,
      published_at: struct.published_at,
      created_at: struct.created_at,
      updated_at: struct.updated_at,
      visibility_group_id: struct.visibility_group_id
    }
  end

  @doc "Base serializer for BookAssociation. Returns a map with all proto fields."
  def book_association(nil), do: nil

  def book_association(%Ecto.Association.NotLoaded{}), do: nil

  def book_association(struct) do
    %{
      id: struct.id,
      book_id: struct.book_id,
      confidence: struct.confidence,
      source: struct.source,
      visible: struct.visible,
      reasoning: struct.reasoning
    }
  end

  @doc "Base serializer for Listing. Returns a map with all proto fields."
  def listing(nil), do: nil

  def listing(%Ecto.Association.NotLoaded{}), do: nil

  def listing(struct) do
    %{
      id: struct.id,
      condition: struct.condition,
      pricing_mode: struct.pricing_mode,
      price_cents: struct.price_cents,
      contact_info: struct.contact_info,
      description: struct.description,
      status: struct.status,
      created_at: struct.created_at,
      currency: struct.currency,
      photo_urls: struct.photo_urls,
      listed_at: struct.listed_at,
      expires_at: struct.expires_at,
      sold_at: struct.sold_at,
      updated_at: struct.updated_at,
      book_id: struct.book_id
    }
  end

  defp format_datetime(nil), do: nil
  defp format_datetime(%DateTime{} = dt), do: DateTime.to_iso8601(dt)
end
