app = "thestacks-log-shipper"
primary_region = "iad"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[build]
  dockerfile = "log-shipper/Dockerfile"

[env]
  ORG = "personal"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"

[[checks]]
  name = "alive"
  type = "http"
  port = 8686
  path = "/health"
  interval = "30s"
  timeout = "5s"
  grace_period = "30s"
