app = "thestacks-scraper"
primary_region = "jnb"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile.scraper"

[env]
  RUST_LOG = "info"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
