"""Fuzz target for image input parsing in the vision sidecar.

Exercises four distinct paths:
  1. _fuzz_base64_and_size   — base64 decode + size check logic (unit level)
  2. _fuzz_model_output_parsing — JSON parsing of Together AI response (unit level)
  3. _fuzz_http_body          — raw bytes as the HTTP request body through the full
                                ASGI stack: FastAPI JSON parsing → Pydantic validation
                                → base64 decode → size check
  4. _fuzz_http_token         — raw bytes as the X-Internal-Token header value,
                                exercising HMAC token parsing with adversarial inputs

Running with Atheris (Linux only — requires: pip install atheris):
    just fuzz-vision -- -atheris_runs=100000

Running as a seed-corpus regression test (all platforms):
    just fuzz-vision

Always invoke via `just fuzz-vision` — the target sets PYTHONPATH=. so that
`app` is importable. Running `python tests/fuzz_image_input.py` directly from
inside `apps/vision/` will fail with ModuleNotFoundError without it.

The seed corpus lives at <repo-root>/images/ and contains representative
book cover photos used to prime coverage before Atheris mutates inputs.
"""

import base64
import hashlib
import hmac as _hmac_mod
import json
import os
import sys
import time
from pathlib import Path
from unittest.mock import AsyncMock, patch

# Must precede app imports — config reads VISION_ENVIRONMENT at module load time.
os.environ.setdefault("VISION_ENVIRONMENT", "test")

# Atheris is Linux-only; import conditionally so the file can be loaded on macOS.
try:
    import atheris

    _ATHERIS_AVAILABLE = True
except ImportError:
    _ATHERIS_AVAILABLE = False

from fastapi.testclient import TestClient

from app.config import settings
from app.main import app

_CORPUS_DIR = Path(__file__).parent.parent.parent.parent / "images"

# Fixed mock responses — HTTP fuzzing exercises request handling, not model calls.
_MOCK_EXTRACT = {"choices": [{"message": {"content": '{"books":[]}'}}]}
_MOCK_CLASSIFY = {
    "choices": [{"message": {"content": '{"classification":"ambiguous","confidence":0.5}'}}]
}

# Patch VisionClient methods permanently so no requests reach Together AI.
# Safe: this file is not collected by pytest (name does not match test_*.py / *_test.py).
_extract_patcher = patch(
    "app.services.vision_client.VisionClient.extract",
    new_callable=AsyncMock,
    return_value=_MOCK_EXTRACT,
)
_classify_patcher = patch(
    "app.services.vision_client.VisionClient.classify",
    new_callable=AsyncMock,
    return_value=_MOCK_CLASSIFY,
)
_extract_patcher.start()
_classify_patcher.start()

# Persistent TestClient — enter lifespan once for the entire fuzzing session.
_http_client = TestClient(app)
_http_client.__enter__()


def _make_auth_header(path: str) -> dict[str, str]:
    ts = str(int(time.time()))
    message = f"{ts}.POST.{path}".encode()
    token = _hmac_mod.new(settings.hmac_secret.encode(), message, hashlib.sha256).hexdigest()
    return {"X-Internal-Token": f"{ts}.{token}"}


def _fuzz_base64_and_size(raw: bytes) -> None:
    """Simulate the per-image validation path shared by /extract and /classify."""
    # Path 1: treat raw bytes as image content, encode and re-decode (nominal path).
    b64 = base64.b64encode(raw).decode()
    try:
        decoded = base64.b64decode(b64, validate=True)
        _ = len(decoded) > settings.max_image_size_bytes
    except Exception:
        pass

    # Path 2: treat raw bytes as an attacker-supplied base64 string.
    try:
        as_str = raw.decode("latin-1")
        decoded = base64.b64decode(as_str, validate=True)
        _ = len(decoded) > settings.max_image_size_bytes
    except Exception:
        pass


def _fuzz_model_output_parsing(raw: bytes) -> None:
    """Simulate the JSON parsing path applied to Together AI model output."""
    try:
        content = raw.decode("utf-8", errors="replace")
        parsed: object = json.loads(content)
        if isinstance(parsed, dict):
            _ = parsed.get("classification", "ambiguous")
            _ = parsed.get("confidence", 0.0)
            raw_books = parsed.get("books")
            if isinstance(raw_books, list):
                for item in raw_books:
                    if isinstance(item, dict):
                        _ = item.get("title")
                        _ = item.get("author")
                        _ = item.get("potential_isbns")
    except (json.JSONDecodeError, UnicodeDecodeError):
        pass


def _fuzz_http_body(raw: bytes) -> None:
    """Send fuzz-generated bytes as the HTTP request body through the full ASGI stack.

    Exercises: FastAPI JSON body parsing, Pydantic model validation, base64 decode,
    and size check — paths not reachable from the unit-level fuzz functions above.
    """
    for path in ("/extract", "/classify"):
        headers = {**_make_auth_header(path), "Content-Type": "application/json"}
        _http_client.post(path, content=raw, headers=headers)


def _fuzz_http_token(raw: bytes) -> None:
    """Send fuzz-generated bytes as the X-Internal-Token header value.

    Exercises: HMAC token parsing with adversarial inputs — missing dots,
    wrong format, very long strings, special characters, invalid timestamps, etc.

    HTTP headers are ASCII-only (RFC 7230), so non-ASCII bytes are filtered to
    printable ASCII (0x20-0x7E) before use. Non-ASCII inputs are discarded at
    the HTTP protocol layer before reaching our auth code, so they add no coverage.
    """
    token_str = "".join(chr(b) for b in raw if 0x20 <= b <= 0x7E)
    if not token_str:
        return
    for path in ("/extract", "/classify"):
        body = {"images": ["dGVzdA=="]} if path == "/extract" else {"image": "dGVzdA=="}
        _http_client.post(path, json=body, headers={"X-Internal-Token": token_str})


def TestOneInput(data: bytes) -> None:  # noqa: N802 — Atheris requires this exact name
    _fuzz_base64_and_size(data)
    _fuzz_model_output_parsing(data)
    _fuzz_http_body(data)
    _fuzz_http_token(data)


def _run_seed_corpus() -> None:
    """Run TestOneInput against every image in the seed corpus plus synthetic inputs."""
    synthetic = [
        b"",
        b"not valid base64!!!",
        b'{"classification": "book", "confidence": 0.95}',
        b'{"classification": "unknown", "confidence": 999}',
        b'{"choices": []}',
        b'{"images": ["dGVzdA=="]}',
        b'{"image": "dGVzdA=="}',
        b'{"images": [null]}',
        b'{"images": [""]}',
        bytes(range(256)),
        b"\x00" * 10_000,
    ]
    for payload in synthetic:
        TestOneInput(payload)

    if _CORPUS_DIR.exists():
        images = sorted(_CORPUS_DIR.glob("*.PNG")) + sorted(_CORPUS_DIR.glob("*.jpg"))
        for img_path in images:
            print(f"  seed: {img_path.name}")
            TestOneInput(img_path.read_bytes())
    else:
        print(f"  (no corpus at {_CORPUS_DIR} — synthetic inputs only)")

    print("Seed corpus run complete — no panics.")


if __name__ == "__main__":
    if _ATHERIS_AVAILABLE and len(sys.argv) > 1 and sys.argv[1].startswith("-"):
        atheris.Setup(sys.argv, TestOneInput)
        atheris.Fuzz()
    else:
        _run_seed_corpus()
