defmodule Mix.Tasks.ProtoSync.DbtGenerator do
  @moduledoc false

  @doc """
  Generates a dbt staging model SQL file from a manifest table entry and proto fields.

  Output is a simple `select ... from {{ source(...) }}` view.
  Column order: id first, then proto fields by field number, then timestamps.
  Skips API-only fields (skip: true) and belongs_to fields (use the _id directly).
  """
  def generate(table, fields) do
    columns = build_column_list(table, fields)
    column_lines = Enum.join(columns, ",\n")

    """
    -- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    -- Source: #{table.proto_file} (#{table.proto_message})
    {{ config(materialized='view') }}

    select
    #{column_lines}
    from {{ source('#{table.schema_prefix}', '#{table.table_name}') }}
    """
  end

  defp build_column_list(table, fields) do
    overrides = Map.get(table, :field_overrides, %{})
    ts_fields = timestamp_field_names(table)

    filtered =
      Enum.reject(fields, fn field ->
        field.name == "id" or field.name in ts_fields or skip_field?(field, overrides)
      end)

    proto_columns = Enum.map(filtered, fn field -> "    #{field.name}" end)
    timestamp_columns = timestamp_cols(table)

    ["    id" | proto_columns] ++ timestamp_columns
  end

  defp timestamp_cols(%{timestamps: :standard}), do: ["    created_at", "    updated_at"]
  defp timestamp_cols(_), do: []

  defp skip_field?(field, overrides) do
    field_name = String.to_atom(field.name)
    override = Map.get(overrides, field_name, %{})
    Map.get(override, :skip, false)
  end

  defp timestamp_field_names(%{timestamps: :standard}), do: ~w(created_at updated_at)
  defp timestamp_field_names(%{timestamps: false}), do: []
  defp timestamp_field_names(_), do: ~w(created_at updated_at)
end
