defmodule Mix.Tasks.ProtoSync.EctoGenerator do
  @moduledoc "Generates read-only Ecto schema modules from proto manifest entries."

  alias Mix.Tasks.ProtoSync.TypeMapper

  @doc """
  Generates an Ecto schema module from a manifest table entry and proto fields.

  Supports:
  - `api_only: true` in field_overrides to exclude API-only fields (no DB column)
  - `belongs_to: ModuleName` in field_overrides to generate belongs_to associations
  - `associations: [{:has_many, name, module, opts}]` in table entry for has_many
  - Standard field generation with type mapping and defaults
  """
  def generate(table, fields) do
    overrides = Map.get(table, :field_overrides, %{})
    module_name = inspect(table.ecto_module)
    ts_fields = timestamp_field_names(table)

    # Partition fields into: belongs_to associations, regular fields, and skipped
    {belongs_to_lines, field_lines} =
      fields
      |> Enum.reject(fn field ->
        field.name == "id" or field.name in ts_fields or api_only_field?(field, overrides)
      end)
      |> Enum.reduce({[], []}, fn field, {bt_acc, f_acc} ->
        field_name = String.to_atom(field.name)
        override = Map.get(overrides, field_name, %{})

        case Map.get(override, :belongs_to) do
          nil ->
            {bt_acc, [field_line(field, overrides) | f_acc]}

          assoc_module ->
            line = belongs_to_line(field, override, assoc_module)
            {[line | bt_acc], f_acc}
        end
      end)

    belongs_to_str = belongs_to_lines |> Enum.reverse() |> Enum.join("\n")
    fields_str = field_lines |> Enum.reverse() |> Enum.join("\n")

    # has_many associations from table-level config
    has_many_lines = has_many_block(table)

    # Combine: belongs_to first, then has_many, then fields
    schema_body =
      [belongs_to_str, has_many_lines, fields_str]
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    timestamps_line = timestamps_block(table)
    virtual_lines = virtual_fields_block(table)

    """
    # Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    # Source: #{table.proto_file} (#{table.proto_message})
    # Regenerate: mix proto.sync
    defmodule #{module_name} do
      @moduledoc false

      use Ecto.Schema

      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
      @schema_prefix "#{table.schema_prefix}"
      @type t :: %__MODULE__{}#{derive_jason_line(table)}

      schema "#{table.table_name}" do
    #{schema_body}#{timestamps_line}#{virtual_lines}
      end
    end
    """
  end

  defp belongs_to_line(field, override, assoc_module) do
    default_name = field.name |> String.replace_suffix("_id", "") |> String.to_atom()
    assoc_name = Map.get(override, :assoc_name, default_name)
    fk_atom = String.to_atom(field.name)

    # When assoc_name differs from default, Ecto can't derive the FK — specify it explicitly.
    opts =
      if assoc_name != default_name,
        do: "type: :binary_id, foreign_key: :#{fk_atom}",
        else: "type: :binary_id"

    "    belongs_to :#{assoc_name}, #{inspect(assoc_module)}, #{opts}"
  end

  defp field_line(field, overrides) do
    type = TypeMapper.ecto_type(field, overrides)
    type_str = format_type(type)
    field_name = String.to_atom(field.name)
    override = Map.get(overrides, field_name, %{})

    # ecto_name: rename the proto field to a different Ecto/DB column name
    ecto_name = Map.get(override, :ecto_name, field_name)

    default_opt =
      case TypeMapper.default(field, overrides) do
        {:ok, value} -> ", default: #{inspect(value)}"
        :none -> ""
      end

    "    field :#{ecto_name}, #{type_str}#{default_opt}"
  end

  defp format_type({:array, inner}), do: "{:array, #{format_type(inner)}}"
  defp format_type(type) when is_atom(type), do: ":#{type}"

  defp format_type(type) do
    raise "Unsupported Ecto type: #{inspect(type)}. Add handling in EctoGenerator.format_type/1."
  end

  defp has_many_block(table) do
    associations = Map.get(table, :associations, [])

    associations
    |> Enum.filter(fn {type, _, _, _} -> type == :has_many end)
    |> Enum.map_join("\n", fn {:has_many, name, module, opts} ->
      opts_str =
        Enum.map_join(opts, ", ", fn
          {k, v} when is_atom(v) -> "#{k}: :#{v}"
          {k, v} -> "#{k}: #{inspect(v)}"
        end)

      "    has_many :#{name}, #{inspect(module)}, #{opts_str}"
    end)
  end

  defp timestamps_block(%{timestamps: false}), do: ""

  defp timestamps_block(%{timestamps: :standard}) do
    "\n\n    timestamps(type: :utc_datetime_usec, inserted_at: :created_at)"
  end

  defp timestamps_block(%{timestamps: {:standard, updated_at: false}}) do
    "\n\n    timestamps(type: :utc_datetime_usec, inserted_at: :created_at, updated_at: false)"
  end

  defp timestamps_block(_), do: ""

  defp api_only_field?(field, overrides) do
    field_name = String.to_atom(field.name)
    override = Map.get(overrides, field_name, %{})
    Map.get(override, :api_only, false)
  end

  defp derive_jason_line(%{derive_jason: fields}) when is_list(fields) do
    field_list = Enum.map_join(fields, ", ", &":#{&1}")
    "\n  @derive {Jason.Encoder, only: [#{field_list}]}"
  end

  defp derive_jason_line(_), do: ""

  defp virtual_fields_block(table) do
    virtuals = Map.get(table, :virtual_fields, [])

    case virtuals do
      [] ->
        ""

      fields ->
        lines =
          Enum.map_join(fields, "\n", fn {name, type} ->
            "    field :#{name}, #{format_type(type)}, virtual: true"
          end)

        "\n#{lines}"
    end
  end

  defp timestamp_field_names(%{timestamps: :standard}), do: ~w(created_at updated_at)
  defp timestamp_field_names(%{timestamps: {:standard, updated_at: false}}), do: ~w(created_at)
  defp timestamp_field_names(%{timestamps: false}), do: []
  defp timestamp_field_names(_), do: ~w(created_at updated_at)
end
