defmodule Mix.Tasks.ProtoSync.EctoGenerator do
  @moduledoc false

  alias Mix.Tasks.ProtoSync.TypeMapper

  @doc """
  Generates a read-only Ecto schema module from a manifest table entry and proto fields.

  The generated schema has no changeset, no `@derive`, and no business logic.
  Context modules own validation and changesets.
  """
  def generate(table, fields) do
    overrides = Map.get(table, :field_overrides, %{})
    module_name = inspect(table.ecto_module)

    field_lines = Enum.map_join(fields, "\n", fn field -> field_line(field, overrides) end)

    timestamps_line = timestamps_block(table)

    """
    # Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    # Source: #{table.proto_file} (#{table.proto_message})
    # Regenerate: mix proto.sync
    defmodule #{module_name} do
      @moduledoc false

      use Ecto.Schema

      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
      @schema_prefix "#{table.schema_prefix}"
      @type t :: %__MODULE__{}

      schema "#{table.table_name}" do
    #{field_lines}#{timestamps_line}
      end
    end
    """
  end

  defp field_line(field, overrides) do
    type = TypeMapper.ecto_type(field, overrides)
    type_str = format_type(type)

    default_opt =
      case TypeMapper.default(field, overrides) do
        {:ok, value} -> ", default: #{inspect(value)}"
        :none -> ""
      end

    "    field :#{field.name}, #{type_str}#{default_opt}"
  end

  defp format_type({:array, inner}), do: "{:array, #{format_type(inner)}}"
  defp format_type(type) when is_atom(type), do: ":#{type}"

  defp timestamps_block(%{timestamps: false}), do: ""

  defp timestamps_block(%{timestamps: :standard}) do
    "\n\n    timestamps(type: :utc_datetime_usec, inserted_at: :created_at)"
  end

  defp timestamps_block(_), do: ""
end
