defmodule Mix.Tasks.ProtoSync.EctoGenerator do
  @moduledoc false

  alias Mix.Tasks.ProtoSync.TypeMapper

  @doc """
  Generates an Ecto schema module from a manifest table entry and proto fields.

  Supports:
  - `skip: true` in field_overrides to exclude API-only fields
  - `belongs_to: ModuleName` in field_overrides to generate belongs_to associations
  - `associations: [{:has_many, name, module, opts}]` in table entry for has_many
  - Standard field generation with type mapping and defaults
  """
  def generate(table, fields) do
    overrides = Map.get(table, :field_overrides, %{})
    module_name = inspect(table.ecto_module)
    ts_fields = timestamp_field_names(table)

    # Partition fields into: belongs_to associations, regular fields, and skipped
    {belongs_to_lines, field_lines} =
      fields
      |> Enum.reject(fn field ->
        field.name == "id" or field.name in ts_fields or skip_field?(field, overrides)
      end)
      |> Enum.reduce({[], []}, fn field, {bt_acc, f_acc} ->
        field_name = String.to_atom(field.name)
        override = Map.get(overrides, field_name, %{})

        case Map.get(override, :belongs_to) do
          nil ->
            {bt_acc, [field_line(field, overrides) | f_acc]}

          assoc_module ->
            # belongs_to: generate the association, skip the _id field
            assoc_name = field.name |> String.replace_suffix("_id", "") |> String.to_atom()
            line = "    belongs_to :#{assoc_name}, #{inspect(assoc_module)}, type: :binary_id"
            {[line | bt_acc], f_acc}
        end
      end)

    belongs_to_str = belongs_to_lines |> Enum.reverse() |> Enum.join("\n")
    fields_str = field_lines |> Enum.reverse() |> Enum.join("\n")

    # has_many associations from table-level config
    has_many_lines = has_many_block(table)

    # Combine: belongs_to first, then has_many, then fields
    schema_body =
      [belongs_to_str, has_many_lines, fields_str]
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    timestamps_line = timestamps_block(table)

    """
    # Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    # Source: #{table.proto_file} (#{table.proto_message})
    # Regenerate: mix proto.sync
    defmodule #{module_name} do
      @moduledoc false

      use Ecto.Schema

      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
      @schema_prefix "#{table.schema_prefix}"
      @type t :: %__MODULE__{}

      schema "#{table.table_name}" do
    #{schema_body}#{timestamps_line}
      end
    end
    """
  end

  defp field_line(field, overrides) do
    type = TypeMapper.ecto_type(field, overrides)
    type_str = format_type(type)

    default_opt =
      case TypeMapper.default(field, overrides) do
        {:ok, value} -> ", default: #{inspect(value)}"
        :none -> ""
      end

    "    field :#{field.name}, #{type_str}#{default_opt}"
  end

  defp format_type({:array, inner}), do: "{:array, #{format_type(inner)}}"
  defp format_type(type) when is_atom(type), do: ":#{type}"

  defp has_many_block(table) do
    associations = Map.get(table, :associations, [])

    associations
    |> Enum.filter(fn {type, _, _, _} -> type == :has_many end)
    |> Enum.map_join("\n", fn {:has_many, name, module, opts} ->
      opts_str = Enum.map_join(opts, ", ", fn {k, v} -> "#{k}: :#{v}" end)
      "    has_many :#{name}, #{inspect(module)}, #{opts_str}"
    end)
  end

  defp timestamps_block(%{timestamps: false}), do: ""

  defp timestamps_block(%{timestamps: :standard}) do
    "\n\n    timestamps(type: :utc_datetime_usec, inserted_at: :created_at)"
  end

  defp timestamps_block(_), do: ""

  defp skip_field?(field, overrides) do
    field_name = String.to_atom(field.name)
    override = Map.get(overrides, field_name, %{})
    Map.get(override, :skip, false)
  end

  defp timestamp_field_names(%{timestamps: :standard}), do: ~w(created_at updated_at)
  defp timestamp_field_names(%{timestamps: false}), do: []
  defp timestamp_field_names(_), do: ~w(created_at updated_at)
end
