defmodule Mix.Tasks.ProtoSync.MigrationGenerator do
  @moduledoc "Generates Ecto migrations and scans existing migrations for column tracking."

  alias Mix.Tasks.ProtoSync.TypeMapper

  @doc """
  Generates an Ecto migration module for a CREATE TABLE statement.

  Only called for tables with `migration_exists: false` in the manifest.
  Tables with `migration_exists: true` already have hand-written migrations.
  """
  def generate_create_table(table, fields, timestamp) do
    overrides = Map.get(table, :field_overrides, %{})
    module_name = migration_module_name(table.table_name, timestamp)

    column_lines =
      fields
      |> Enum.map_join("\n", fn field -> column_line(field, overrides) end)

    timestamps_line = timestamps_block(table)
    index_lines = index_block(table)
    grant_lines = grant_block(table)

    """
    # Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    # Source: #{table.proto_file} (#{table.proto_message})
    # Regenerate: mix proto.sync
    defmodule #{module_name} do
      use Ecto.Migration

      def up do
        create table(:#{table.table_name}, prefix: "#{table.schema_prefix}", primary_key: false) do
          add :id, :binary_id, primary_key: true
    #{column_lines}#{timestamps_line}
        end
    #{index_lines}#{grant_lines}  end

      def down do
        drop table(:#{table.table_name}, prefix: "#{table.schema_prefix}")
      end
    end
    """
  end

  @doc """
  Generates an Ecto migration module for ALTER TABLE ADD COLUMN statements.

  Called when proto fields exist that are not in the current migration history.
  """
  def generate_add_columns(table, new_fields, timestamp) do
    overrides = Map.get(table, :field_overrides, %{})
    slug = Enum.map_join(new_fields, "_", & &1.name)
    module_name = migration_module_name("add_#{slug}_to_#{table.table_name}", timestamp)

    column_lines =
      new_fields
      |> Enum.map_join("\n", fn field -> column_line(field, overrides) end)

    down_lines =
      Enum.map_join(new_fields, "\n", fn field ->
        field_name = String.to_atom(field.name)
        override = Map.get(overrides, field_name, %{})
        col_name = Map.get(override, :ecto_name, field_name)
        "      remove :#{col_name}"
      end)

    """
    # Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    # Source: #{table.proto_file} (#{table.proto_message})
    # Regenerate: mix proto.sync
    defmodule #{module_name} do
      use Ecto.Migration

      def up do
        alter table(:#{table.table_name}, prefix: "#{table.schema_prefix}") do
    #{column_lines}
        end
      end

      def down do
        alter table(:#{table.table_name}, prefix: "#{table.schema_prefix}") do
    #{down_lines}
        end
      end
    end
    """
  end

  @doc """
  Scans existing migration files to find which columns already exist for a table.

  Returns a MapSet of column name strings.
  """
  def existing_columns(migrations_dir, table_name) do
    if File.dir?(migrations_dir) do
      {all_added, all_removed} =
        migrations_dir
        |> File.ls!()
        |> Enum.filter(&String.ends_with?(&1, ".exs"))
        |> Enum.sort()
        |> Enum.reduce({[], []}, fn file, {adds, removes} ->
          {a, r} = columns_from_file(file, migrations_dir, table_name)
          {adds ++ a, removes ++ r}
        end)

      (all_added -- all_removed)
      |> MapSet.new()
    else
      MapSet.new()
    end
  end

  defp columns_from_file(file, migrations_dir, table_name) do
    content = File.read!(Path.join(migrations_dir, file))

    if mentions_table?(content, table_name) do
      extract_columns_for_table(content, table_name)
    else
      {[], []}
    end
  end

  @doc """
  Generates a migration timestamp string (YYYYMMDDhhmmss).
  """
  def generate_timestamp do
    {{y, m, d}, {h, min, s}} = :calendar.universal_time()

    :io_lib.format("~4..0B~2..0B~2..0B~2..0B~2..0B~2..0B", [y, m, d, h, min, s])
    |> IO.iodata_to_binary()
  end

  # --- Private helpers ---

  defp column_line(field, overrides) do
    field_name = String.to_atom(field.name)
    override = Map.get(overrides, field_name, %{})
    col_name = Map.get(override, :ecto_name, field_name)

    type = TypeMapper.migration_type(field, overrides)
    type_str = format_migration_type(type)
    opts = column_opts(field, overrides)
    opts_str = if opts == "", do: "", else: ", #{opts}"

    "      add :#{col_name}, #{type_str}#{opts_str}"
  end

  defp column_opts(field, overrides) do
    field_name = String.to_atom(field.name)
    override = Map.get(overrides, field_name, %{})

    opts = []

    opts =
      case Map.get(override, :null) do
        false -> ["null: false" | opts]
        _ -> opts
      end

    opts =
      case Map.get(override, :default) do
        nil -> opts
        {:fragment, sql} -> ["default: fragment(#{inspect(sql)})" | opts]
        value -> ["default: #{inspect(value)}" | opts]
      end

    opts
    |> Enum.reverse()
    |> Enum.join(", ")
  end

  defp format_migration_type({:array, inner}), do: "{:array, #{format_migration_type(inner)}}"
  defp format_migration_type(type) when is_atom(type), do: ":#{type}"

  defp format_migration_type(type) do
    raise "Unsupported migration type: #{inspect(type)}. Add handling in MigrationGenerator.format_migration_type/1."
  end

  defp timestamps_block(%{timestamps: false}), do: ""

  defp timestamps_block(%{timestamps: :standard}) do
    "\n\n      timestamps(type: :utc_datetime_usec)"
  end

  defp timestamps_block(_), do: ""

  defp index_block(table) do
    indexes = Map.get(table, :indexes, [])

    if indexes == [] do
      ""
    else
      lines = Enum.map_join(indexes, "\n", &format_index_line(&1, table))

      "\n#{lines}\n"
    end
  end

  defp format_index_line(idx, table) do
    if Map.get(idx, :unique, false) do
      cols = format_index_columns(idx.columns)

      "    create unique_index(:#{table.table_name}, #{cols}, prefix: \"#{table.schema_prefix}\")"
    else
      col_sql = format_index_sql(table, idx)
      "\n    execute(#{inspect(col_sql)})"
    end
  end

  defp format_index_sql(table, idx) do
    cols =
      Enum.map_join(idx.columns, ", ", fn
        {:desc, col} -> "#{col} DESC"
        col when is_atom(col) -> "#{col}"
      end)

    "CREATE INDEX #{idx.name} ON #{table.schema_prefix}.#{table.table_name} (#{cols})"
  end

  defp format_index_columns(columns) do
    cols =
      Enum.map_join(columns, ", ", fn
        {:desc, col} -> ":#{col}"
        col when is_atom(col) -> ":#{col}"
      end)

    "[#{cols}]"
  end

  defp grant_block(%{dbt_grant: true} = table) do
    """

        execute(
          \"\"\"
          DO $$ BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
              GRANT SELECT ON #{table.schema_prefix}.#{table.table_name} TO stacks_dbt;
            END IF;
          END $$;
          \"\"\",
          \"\"\"
          DO $$ BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
              REVOKE SELECT ON #{table.schema_prefix}.#{table.table_name} FROM stacks_dbt;
            END IF;
          END $$;
          \"\"\"
        )
    """
  end

  defp grant_block(_), do: ""

  defp migration_module_name(slug, timestamp) do
    camelized =
      slug
      |> to_string()
      |> String.split("_")
      |> Enum.map_join(&String.capitalize/1)

    "Core.Repo.Migrations.#{camelized}#{timestamp}"
  end

  defp mentions_table?(content, table_name) do
    String.contains?(content, ":#{table_name}") or
      String.contains?(content, "\"#{table_name}\"")
  end

  # Extracts columns belonging to a specific table by finding `create table`
  # or `alter table` blocks for that table name and only scanning within them.
  # Only considers blocks in `def up do...end` — ignores `def down do...end`.
  defp extract_columns_for_table(content, table_name) do
    # Extract forward-migration body: `def up do...end` or `def change do...end`.
    # Avoids counting `def down` removes as additions.
    up_content =
      case Regex.run(~r/def up do\n(.*?)(?=\n\s+def down\b|\n\s+end\n\z)/s, content) do
        [_, body] ->
          body

        _ ->
          case Regex.run(~r/def change do\n(.*?)(?=\n\s+end\n\z)/s, content) do
            [_, body] -> body
            _ -> content
          end
      end

    # Match blocks like: create table(:table_name, ...) do ... end
    # or: alter table(:table_name, ...) do ... end
    # Match `end` only at start of line (indented) to avoid matching `on_delete: :delete_all`.
    table_pattern =
      ~r/(?:create|alter)\s+table\(:#{Regex.escape(table_name)}\b[^)]*\)\s+do(.*?)^\s+end/ms

    blocks = Regex.scan(table_pattern, up_content)

    added =
      Enum.flat_map(blocks, fn [_, block] ->
        ~r/^\s+add\s+:(\w+)/m
        |> Regex.scan(block)
        |> Enum.map(fn [_, col] -> col end)
        |> Enum.reject(&(&1 == "id"))
      end)

    removed =
      Enum.flat_map(blocks, fn [_, block] ->
        ~r/^\s+remove\s+:(\w+)/m
        |> Regex.scan(block)
        |> Enum.map(fn [_, col] -> col end)
      end)

    {added, removed}
  end
end
