defmodule Mix.Tasks.ProtoSync.MigrationGenerator do
  @moduledoc "Generates Ecto migrations and scans existing migrations for column tracking."

  alias Mix.Tasks.ProtoSync.TypeMapper

  @doc """
  Generates an Ecto migration module for a CREATE TABLE statement.

  Only called for tables with `migration_exists: false` in the manifest.
  Tables with `migration_exists: true` already have hand-written migrations.
  """
  def generate_create_table(table, fields, timestamp) do
    overrides = Map.get(table, :field_overrides, %{})
    module_name = migration_module_name(table.table_name, timestamp)

    ts_fields = timestamp_field_names(table)

    column_lines =
      fields
      |> Enum.reject(fn field -> field.name == "id" or field.name in ts_fields end)
      |> Enum.map_join("\n", fn field -> column_line(field, overrides, table.schema_prefix) end)

    timestamps_line = timestamps_block(table)
    index_lines = index_block(table)
    grant_lines = grant_block(table)

    """
    # Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    # Source: #{table.proto_file} (#{table.proto_message})
    # Regenerate: mix proto.sync
    defmodule #{module_name} do
      use Ecto.Migration

      # `CREATE INDEX CONCURRENTLY` cannot run inside a transaction, so opt
      # out of Ecto's default migration-wide transaction.
      @disable_ddl_transaction true

      # Ecto holds its advisory migration lock on a separate idle connection
      # for the full CONCURRENTLY build. Neon's managed Postgres drops idle
      # TCP sockets on its own keepalive window, surfacing as a 300s hang +
      # `ssl send: closed` on fresh envs (observed 2026-04-22 bootstrapping
      # the staging project). Disabling the lock prevents that; deploys are
      # already serialised by the release pipeline.
      @disable_migration_lock true

      def up do
        create table(:#{table.table_name}, prefix: "#{table.schema_prefix}", primary_key: false) do
          add :id, :binary_id, primary_key: true
    #{column_lines}#{timestamps_line}
        end
    #{index_lines}#{grant_lines}  end

      def down do
        drop table(:#{table.table_name}, prefix: "#{table.schema_prefix}")
      end
    end
    """
  end

  @doc """
  Generates an Ecto migration module for ALTER TABLE ADD COLUMN statements.

  Called when proto fields exist that are not in the current migration history.
  """
  def generate_add_columns(table, new_fields, timestamp) do
    overrides = Map.get(table, :field_overrides, %{})
    slug = Enum.map_join(new_fields, "_", & &1.name)
    module_name = migration_module_name("add_#{slug}_to_#{table.table_name}", timestamp)

    column_lines =
      new_fields
      |> Enum.map_join("\n", fn field -> column_line(field, overrides, table.schema_prefix) end)

    down_lines =
      Enum.map_join(new_fields, "\n", fn field ->
        field_name = String.to_atom(field.name)
        override = Map.get(overrides, field_name, %{})
        col_name = Map.get(override, :ecto_name, field_name)
        "      remove :#{col_name}"
      end)

    """
    # Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    # Source: #{table.proto_file} (#{table.proto_message})
    # Regenerate: mix proto.sync
    defmodule #{module_name} do
      use Ecto.Migration

      def up do
        alter table(:#{table.table_name}, prefix: "#{table.schema_prefix}") do
    #{column_lines}
        end
      end

      def down do
        alter table(:#{table.table_name}, prefix: "#{table.schema_prefix}") do
    #{down_lines}
        end
      end
    end
    """
  end

  @doc """
  Scans existing migration files to find which columns already exist for a table.

  Returns a MapSet of column name strings.
  """
  def existing_columns(migrations_dir, table_name) do
    if File.dir?(migrations_dir) do
      {all_added, all_removed} =
        migrations_dir
        |> File.ls!()
        |> Enum.filter(&String.ends_with?(&1, ".exs"))
        |> Enum.sort()
        |> Enum.reduce({[], []}, fn file, {adds, removes} ->
          {a, r} = columns_from_file(file, migrations_dir, table_name)
          {adds ++ a, removes ++ r}
        end)

      (all_added -- all_removed)
      |> MapSet.new()
    else
      MapSet.new()
    end
  end

  defp columns_from_file(file, migrations_dir, table_name) do
    content = File.read!(Path.join(migrations_dir, file))

    if mentions_table?(content, table_name) do
      extract_columns_for_table(content, table_name)
    else
      {[], []}
    end
  end

  @doc """
  Generates a migration timestamp string (YYYYMMDDhhmmss).
  """
  def generate_timestamp do
    {{y, m, d}, {h, min, s}} = :calendar.universal_time()

    :io_lib.format("~4..0B~2..0B~2..0B~2..0B~2..0B~2..0B", [y, m, d, h, min, s])
    |> IO.iodata_to_binary()
  end

  # --- Private helpers ---

  defp column_line(field, overrides, schema_prefix) do
    field_name = String.to_atom(field.name)
    override = Map.get(overrides, field_name, %{})
    col_name = Map.get(override, :ecto_name, field_name)

    type_str =
      case Map.get(override, :references_table) do
        nil ->
          type = TypeMapper.migration_type(field, overrides)
          format_migration_type(type)

        ref_table ->
          on_delete = Map.get(override, :on_delete, :nothing)

          "references(:#{ref_table}, type: :binary_id, prefix: \"#{schema_prefix}\", on_delete: :#{on_delete})"
      end

    opts = column_opts(field, overrides)
    opts_str = if opts == "", do: "", else: ", #{opts}"

    "      add :#{col_name}, #{type_str}#{opts_str}"
  end

  defp column_opts(field, overrides) do
    field_name = String.to_atom(field.name)
    override = Map.get(overrides, field_name, %{})

    opts = []

    opts =
      case Map.get(override, :null) do
        false -> ["null: false" | opts]
        _ -> opts
      end

    opts =
      case Map.get(override, :default) do
        nil -> opts
        {:fragment, sql} -> ["default: fragment(#{inspect(sql)})" | opts]
        value -> ["default: #{inspect(value)}" | opts]
      end

    opts
    |> Enum.reverse()
    |> Enum.join(", ")
  end

  defp format_migration_type({:array, inner}), do: "{:array, #{format_migration_type(inner)}}"
  defp format_migration_type(type) when is_atom(type), do: ":#{type}"

  defp format_migration_type(type) do
    raise "Unsupported migration type: #{inspect(type)}. Add handling in MigrationGenerator.format_migration_type/1."
  end

  defp timestamp_field_names(%{timestamps: :standard}), do: ~w(created_at updated_at)
  defp timestamp_field_names(%{timestamps: {:standard, updated_at: false}}), do: ~w(created_at)
  defp timestamp_field_names(%{timestamps: false}), do: []
  defp timestamp_field_names(_), do: ~w(created_at updated_at)

  defp timestamps_block(%{timestamps: false}), do: ""

  defp timestamps_block(%{timestamps: :standard}) do
    "\n\n      timestamps(type: :utc_datetime_usec)"
  end

  # Append-only tables (`updated_at: false`) still need the `created_at` column.
  # Without this clause the catch-all emitted no timestamps block, so the
  # generated migration lacked `created_at` while the generated Ecto schema
  # (EctoGenerator handles this case) expected it — an insert-time mismatch.
  defp timestamps_block(%{timestamps: {:standard, updated_at: false}}) do
    "\n\n      timestamps(type: :utc_datetime_usec, updated_at: false)"
  end

  defp timestamps_block(_), do: ""

  defp index_block(table) do
    overrides = Map.get(table, :field_overrides, %{})
    explicit_indexes = Map.get(table, :indexes, [])

    # Columns already served by an explicit single-column index. The auto FK
    # index on such a column would be an exact duplicate (a single-column
    # unique index — the upsert conflict target — fully covers FK lookups), so
    # suppress it. Composite indexes are left alone: their leading column is a
    # separate optimization decision, not an exact cover (Issue #266).
    fk_columns_with_index =
      for %{columns: [col]} <- explicit_indexes, into: MapSet.new(), do: col

    fk_lines =
      overrides
      |> Enum.filter(fn {_, override} -> Map.has_key?(override, :references_table) end)
      |> Enum.reject(fn {field_name, _} -> MapSet.member?(fk_columns_with_index, field_name) end)
      |> Enum.sort_by(fn {field_name, _} -> field_name end)
      |> Enum.map_join("\n", fn {field_name, _} ->
        # Foreign-key indexes are always non-unique, named implicitly by Ecto.
        # `concurrently: true` keeps the lint-clean invariant uniform across
        # every index this generator emits.
        "    create index(:#{table.table_name}, [:#{field_name}], prefix: \"#{table.schema_prefix}\", concurrently: true)"
      end)

    explicit_lines =
      explicit_indexes
      |> Enum.map_join("\n", &format_index_line(&1, table))

    all_lines = [fk_lines, explicit_lines] |> Enum.reject(&(&1 == "")) |> Enum.join("\n")

    if all_lines == "" do
      ""
    else
      "\n#{all_lines}\n"
    end
  end

  # Every generated index uses `concurrently: true`. Squawk enforces this in
  # CI; more importantly, CONCURRENTLY lets Postgres build the index without
  # blocking writes, which is the safe default for any future additions to
  # already-populated tables.
  defp format_index_line(idx, table) do
    cols = format_index_columns(idx.columns)
    prefix = table.schema_prefix
    base = "(:#{table.table_name}, #{cols}, prefix: \"#{prefix}\""
    tail = ", name: \"#{idx.name}\", concurrently: true)"

    if Map.get(idx, :unique, false) do
      "    create unique_index" <> base <> tail
    else
      "    create index" <> base <> tail
    end
  end

  defp format_index_columns(columns) do
    cols =
      Enum.map_join(columns, ", ", fn
        # Ecto's `create index` supports mixed asc/desc columns via keyword
        # syntax: `[:a, :b, desc: :c]` for `a, b, c DESC`. Keyword members
        # must come after positional atoms, which is how the manifest
        # declares them in practice (descending columns are conventionally
        # last, e.g. `{:desc, :occurred_at}`).
        {:desc, col} -> "desc: :#{col}"
        col when is_atom(col) -> ":#{col}"
      end)

    "[#{cols}]"
  end

  defp grant_block(%{dbt_grant: true} = table) do
    """

        execute(
          \"\"\"
          DO $$ BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
              GRANT SELECT ON #{table.schema_prefix}.#{table.table_name} TO stacks_dbt;
            END IF;
          END $$;
          \"\"\",
          \"\"\"
          DO $$ BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
              REVOKE SELECT ON #{table.schema_prefix}.#{table.table_name} FROM stacks_dbt;
            END IF;
          END $$;
          \"\"\"
        )
    """
  end

  defp grant_block(_), do: ""

  defp migration_module_name(slug, timestamp) do
    camelized =
      slug
      |> to_string()
      |> String.split("_")
      |> Enum.map_join(&String.capitalize/1)

    "Core.Repo.Migrations.#{camelized}#{timestamp}"
  end

  defp mentions_table?(content, table_name) do
    String.contains?(content, ":#{table_name}") or
      String.contains?(content, "\"#{table_name}\"")
  end

  # Extracts columns belonging to a specific table by finding `create table`
  # or `alter table` blocks for that table name and only scanning within them.
  # Only considers blocks in `def up do...end` — ignores `def down do...end`.
  defp extract_columns_for_table(content, table_name) do
    # Extract forward-migration body: `def up do...end` or `def change do...end`.
    # Avoids counting `def down` removes as additions.
    up_content =
      case Regex.run(~r/def up do\n(.*?)(?=\n\s+def down\b|\n\s+end\n\z)/s, content) do
        [_, body] ->
          body

        _ ->
          case Regex.run(~r/def change do\n(.*?)(?=\n\s+end\n\z)/s, content) do
            [_, body] -> body
            _ -> content
          end
      end

    # Match blocks like: create table(:table_name, ...) do ... end
    # or: alter table(:table_name, ...) do ... end
    # Match `end` only at start of line (indented) to avoid matching `on_delete: :delete_all`.
    table_pattern =
      ~r/(?:create|alter)\s+table\(:#{Regex.escape(table_name)}\b[^)]*\)\s+do(.*?)^\s+end/ms

    blocks = Regex.scan(table_pattern, up_content)

    added =
      Enum.flat_map(blocks, fn [_, block] ->
        ~r/^\s+add(?:_if_not_exists)?\s+:(\w+)/m
        |> Regex.scan(block)
        |> Enum.map(fn [_, col] -> col end)
        |> Enum.reject(&(&1 == "id"))
      end)

    removed =
      Enum.flat_map(blocks, fn [_, block] ->
        ~r/^\s+remove\s+:(\w+)/m
        |> Regex.scan(block)
        |> Enum.map(fn [_, col] -> col end)
      end)

    {added, removed}
  end
end
