defmodule Mix.Tasks.ProtoSync.ProtoJsonGenerator do
  @moduledoc "Generates ProtoJSON.Gen base serializer functions from proto message definitions."

  alias Mix.Tasks.ProtoSync.Descriptor

  @doc """
  Generates the ProtoJSON.Gen module with one function per proto message.

  Each function extracts all fields from an Ecto struct and returns a map
  with keys matching the proto `json_name` annotations. Controllers compose
  these base functions with business logic in the hand-written ProtoJSON module.

  Uses the `proto_json` manifest config to determine which messages to generate
  and how to map Ecto struct fields to JSON keys.
  """
  def generate(manifest, descriptor) do
    configs = Map.get(manifest, :proto_json, [])

    functions =
      configs
      |> Enum.map(&generate_function(&1, descriptor))
      |> Enum.map(&String.trim_trailing/1)

    """
    # Generated by mix proto.sync — DO NOT EDIT MANUALLY.
    # Regenerate: mix proto.sync
    defmodule StacksWeb.ProtoJSON.Gen do
      @moduledoc "Proto-generated base serializers. Use StacksWeb.ProtoJSON for the public API."

    #{Enum.join(functions, "\n\n")}

      defp format_datetime(nil), do: nil
      defp format_datetime(%DateTime{} = dt), do: DateTime.to_iso8601(dt)
    end
    """
  end

  defp generate_function(config, descriptor) do
    fields = Descriptor.extract_fields(descriptor, config.proto_file, config.proto_message)
    overrides = Map.get(config, :field_overrides, %{})
    skip_fields = Map.get(config, :skip_fields, [])

    # Build field lines: extract from struct, map to json_name
    field_lines =
      fields
      |> Enum.reject(fn f -> f.name == "id" or String.to_atom(f.name) in skip_fields end)
      |> Enum.map(fn field ->
        field_atom = String.to_atom(field.name)
        override = Map.get(overrides, field_atom, %{})

        # Ecto struct field name (may differ from proto via ecto_name)
        ecto_name = Map.get(override, :ecto_name, field_atom)
        # JSON output key (from proto json_name, defaults to field name)
        json_key = field.json_name || field.name

        accessor = "struct.#{ecto_name}"

        # Type coercion
        value_expr =
          case coerce_type(field) do
            :datetime -> "format_datetime(#{accessor})"
            :identity -> accessor
          end

        "      #{json_key}: #{value_expr}"
      end)

    fn_name = config.function_name
    id_line = "      id: struct.id"
    all_lines = [id_line | field_lines] |> Enum.join(",\n")

    """
      @doc "Base serializer for #{config.proto_message}. Returns a map with all proto fields."
      def #{fn_name}(nil), do: nil

      def #{fn_name}(%Ecto.Association.NotLoaded{}), do: nil

      def #{fn_name}(struct) do
        %{
    #{all_lines}
        }
      end
    """
  end

  defp coerce_type(%{type: "TYPE_MESSAGE", type_name: "." <> name}) do
    if String.ends_with?(name, "Timestamp"), do: :datetime, else: :identity
  end

  defp coerce_type(_), do: :identity
end
