-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/placement.proto (Bookshelf)
{{ config(materialized='view') }}

select
    id,
    user_id,
    name,
    visibility,
    visibility_group_id,
    created_at,
    updated_at
from {{ source('op', 'bookshelves') }}
