-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/enrichment.proto (DiscoveredSource)
{{ config(materialized='view') }}

select
    id,
    name,
    type,
    url,
    confidence,
    discovered_via,
    discovered_at,
    status,
    approved_at,
    config_generated,
    excluded_at,
    exclusion_requested_at,
    created_at,
    updated_at
from {{ source('op', 'discovered_sources') }}
