-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/writing_assistant.proto (TurnFeedback)
{{ config(materialized='view') }}

select
    id,
    session_id,
    turn_index,
    rating,
    comment,
    created_at
from {{ source('op', 'turn_feedback') }}
