-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/enrichment.proto (Bookstore)
{{ config(materialized='view') }}

select
    id,
    name,
    website_url,
    search_template,
    has_physical,
    country_code,
    scraper_module,
    price_source,
    isbn_location,
    lookup_mode,
    capability_probed_at,
    canary_isbn,
    robots_blocked_path,
    robots_blocked_rule,
    robots_blocked_at,
    unscrapable_reason,
    latitude,
    longitude,
    events_path,
    events_path_checked_at,
    events_unresolved_reason,
    events_page_etag,
    events_page_last_modified,
    created_at,
    updated_at
from {{ source('op', 'bookstores') }}
