-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/enrichment.proto (ThirdSpace)
{{ config(materialized='view') }}

select
    id,
    name,
    type,
    city,
    country_code,
    instagram_url,
    website_url,
    description,
    discovered_via,
    verified,
    last_active_at,
    opted_out,
    opted_out_at,
    latitude,
    longitude,
    nearest_bookshop_km,
    created_at,
    updated_at
from {{ source('op', 'third_spaces') }}
