-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/blog.proto (PostComment)
{{ config(materialized='view') }}

select
    id,
    post_id,
    author_id,
    parent_id,
    body,
    created_at
from {{ source('op', 'post_comments') }}
