-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/enrichment.proto (ReviewSnapshot)
{{ config(materialized='view') }}

select
    id,
    book_id,
    source,
    source_url,
    sentiment_score,
    summary,
    rating,
    rating_count,
    scraped_at,
    stale_after
from {{ source('op', 'review_snapshots') }}
