-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/social.proto (GroupInvitation)
{{ config(materialized='view') }}

select
    id,
    group_id,
    invited_by_id,
    invited_user_id,
    status,
    responded_at,
    created_at
from {{ source('op', 'group_invitations') }}
