-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/social.proto (Group)
{{ config(materialized='view') }}

select
    id,
    owner_id,
    name,
    type,
    visibility,
    created_at,
    updated_at
from {{ source('op', 'groups') }}
