-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/internal/v1/audit.proto (AuditEntry)
{{ config(materialized='view') }}

select
    id,
    user_id,
    action,
    resource_type,
    resource_id,
    occurred_at,
    endpoint,
    latency_ms,
    success,
    row_count,
    operator_session_id
from {{ source('audit', 'audit_log') }}
