-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/writing_assistant.proto (RetrievalLog)
{{ config(materialized='view') }}

select
    id,
    session_id,
    retrieved_ids,
    scores,
    turn_index,
    created_at
from {{ source('op', 'retrieval_log') }}
