-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/upload.proto (UploadedImage)
{{ config(materialized='view') }}

select
    id,
    status,
    rejection_reason,
    uploaded_at,
    expires_at,
    book_ids,
    book_id,
    book_edition_id,
    user_id,
    created_at,
    updated_at
from {{ source('op', 'uploaded_images') }}
