-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/writing_assistant.proto (BlogAssistantSession)
{{ config(materialized='view') }}

select
    id,
    user_id,
    status,
    topic,
    model,
    started_at,
    created_at,
    updated_at
from {{ source('op', 'blog_assistant_sessions') }}
