-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/listing.proto (Listing)
{{ config(materialized='view') }}

select
    id,
    condition,
    pricing_mode,
    price_cents,
    contact_info,
    description,
    status,
    currency,
    photo_urls,
    listed_at,
    expires_at,
    sold_at,
    book_id,
    seller_id,
    created_at,
    updated_at
from {{ source('op', 'listings') }}
