-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/book.proto (Author)
{{ config(materialized='view') }}

select
    id,
    name,
    website_url,
    rss_feed_url,
    bio,
    open_library_id,
    created_at,
    updated_at
from {{ source('op', 'authors') }}
