-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/internal/v1/book_cache.proto (IsbnResolverCacheEntry)
{{ config(materialized='view') }}

select
    id,
    isbn,
    outcome,
    metadata,
    expires_at,
    created_at,
    updated_at
from {{ source('op', 'isbn_resolver_cache') }}
