-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/social.proto (UserBlock)
{{ config(materialized='view') }}

select
    id,
    blocker_id,
    blocked_id,
    created_at
from {{ source('op', 'user_blocks') }}
