-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/writing_assistant.proto (UserBookContentAccess)
{{ config(materialized='view') }}

select
    id,
    user_id,
    book_id,
    access_type,
    granted_at,
    created_at
from {{ source('op', 'user_book_content_access') }}
