-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/import.proto (LibraryImport)
{{ config(materialized='view') }}

select
    id,
    user_id,
    source,
    status,
    row_count,
    processed_count,
    shelved_count,
    duplicate_count,
    unverified_count,
    unreadable_count,
    started_at,
    finished_at,
    created_at,
    updated_at
from {{ source('op', 'library_imports') }}
