-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/blog.proto (BookAssociation)
{{ config(materialized='view') }}

select
    id,
    book_id,
    confidence,
    source,
    visible,
    reasoning,
    post_id,
    created_at
from {{ source('op', 'post_book_associations') }}
