-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/blog.proto (PostSyndication)
{{ config(materialized='view') }}

select
    id,
    post_id,
    target,
    method,
    canonical_url,
    syndicated_url,
    created_at
from {{ source('op', 'post_syndications') }}
