-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/internal/v1/partner.proto (Partner)
{{ config(materialized='view') }}

select
    id,
    name,
    business_type,
    contact_email,
    website_url,
    status,
    api_key_prefix,
    approved_by_id,
    approved_at,
    third_space_id,
    created_at,
    updated_at
from {{ source('op', 'partners') }}
