-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/internal/v1/book_cache.proto (TitleSearchCacheEntry)
{{ config(materialized='view') }}

select
    id,
    cache_key,
    title,
    author,
    raw_text,
    outcome,
    isbn,
    metadata,
    expires_at,
    created_at,
    updated_at
from {{ source('op', 'title_search_cache') }}
