-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/internal/v1/partner.proto (PartnerInventoryItem)
{{ config(materialized='view') }}

select
    id,
    partner_id,
    book_edition_id,
    price_cents,
    condition,
    quantity,
    synced_at,
    created_at,
    updated_at
from {{ source('op', 'partner_inventory') }}
