-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/enrichment.proto (PriceSnapshot)
{{ config(materialized='view') }}

select
    id,
    book_id,
    store_id,
    price_cents,
    currency,
    in_stock,
    url,
    scraped_at
from {{ source('op', 'price_snapshots') }}
