-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/blog.proto (BlogPost)
{{ config(materialized='view') }}

select
    id,
    title,
    body,
    visibility,
    user_id,
    published_at,
    visibility_group_id,
    created_at,
    updated_at
from {{ source('op', 'blog_posts') }}
