-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/marketplace.proto (OfferMessage)
{{ config(materialized='view') }}

select
    id,
    thread_id,
    sender_id,
    type,
    amount_cents,
    created_at
from {{ source('op', 'offer_messages') }}
