-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/placement.proto (Shelf)
{{ config(materialized='view') }}

select
    id,
    bookshelf_id,
    position,
    created_at
from {{ source('op', 'shelves') }}
