-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/book.proto (Edition)
{{ config(materialized='view') }}

select
    id,
    isbn,
    is_primary,
    cover_image_url,
    page_count,
    publisher,
    publication_year,
    format_label,
    open_library_id,
    google_books_id,
    book_id,
    verification_source,
    created_at,
    updated_at
from {{ source('op', 'book_editions') }}
