-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/placement.proto (PlacementHistory)
{{ config(materialized='view') }}

select
    id,
    book_id,
    from_bookshelf,
    to_bookshelf,
    moved_at
from {{ source('op', 'bookshelf_placement_history') }}
