-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/costs.proto (PlatformCost)
{{ config(materialized='view') }}

select
    id,
    category,
    service,
    description,
    amount_cents,
    currency,
    period_start,
    period_end,
    created_at,
    updated_at
from {{ source('op', 'platform_costs') }}
