-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/user.proto (InviteCode)
{{ config(materialized='view') }}

select
    id,
    code_prefix,
    issued_by_id,
    max_uses,
    use_count,
    expires_at,
    redeemed_by_id,
    redeemed_at,
    revoked_at,
    created_at,
    updated_at
from {{ source('op', 'invite_codes') }}
