-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/enrichment.proto (ThirdSpaceEvent)
{{ config(materialized='view') }}

select
    id,
    space_id,
    title,
    description,
    event_date,
    recurrence,
    related_authors,
    source_url,
    scraped_at
from {{ source('op', 'third_space_events') }}
