-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/user.proto (User)
{{ config(materialized='view') }}

select
    id,
    email,
    display_name,
    role,
    country_code,
    city,
    consent_analytics,
    age_verified,
    profile_visibility,
    website_url,
    consent_analytics_at,
    onboarding_completed,
    notify_wishlist_availability,
    notify_marketplace,
    notify_group_invitations,
    notify_event_matches,
    email_confirmed,
    age_verified_at,
    age_verification_provider,
    onboarding_steps,
    consent_writing_assistant,
    consent_writing_assistant_at,
    created_at,
    updated_at
from {{ source('op', 'users') }}
