-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/internal/v1/audit.proto (AuditEntry)
{{ config(materialized='view') }}

select
    id,
    user_id,
    action,
    resource_type,
    resource_id,
    ip_address,
    metadata,
    occurred_at
from {{ source('audit', 'audit_log') }}
