-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/enrichment.proto (BookstoreEvent)
{{ config(materialized='view') }}

select
    id,
    store_id,
    author_id,
    title,
    description,
    event_date,
    location,
    url,
    scraped_at
from {{ source('op', 'bookstore_events') }}
