-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/enrichment.proto (Bookstore)
{{ config(materialized='view') }}

select
    id,
    name,
    website_url,
    search_template,
    has_physical,
    country_code,
    scraper_module,
    created_at,
    updated_at
from {{ source('op', 'bookstores') }}
