-- Generated by mix proto.sync — DO NOT EDIT MANUALLY.
-- Source: stacks/common/v1/book.proto (Book)
{{ config(materialized='view') }}

select
    id,
    title,
    author_id,
    description,
    subjects,
    visibility_tier,
    language,
    bisac_codes,
    created_at,
    updated_at
from {{ source('op', 'books') }}
