#!/usr/bin/env bash
# Every script has a caller, and the inventory that says so is generated.
#
# scripts/ had grown to 93 files, of which six had NO caller anywhere — three
# were superseded twins of logic that had moved inline (a second deploy path is
# a drift machine), one duplicated an MCP capability, and the MCP server's own
# test suite had NEVER RUN: on its first execution, three tests failed, one
# because a repo-wide sweep had mutilated its fixtures and nothing noticed.
# "Exists in scripts/" said nothing about "runs anywhere".
#
# WHAT IT CHECKS  Every file under scripts/ is referenced by at least one
# caller (justfile, .github workflows/actions, hooks, another script, e2e,
# mix.exs, .mcp.json) or carries an ALLOWLIST entry naming why it is manual.
# It also regenerates scripts/README.md — the inventory of what calls what —
# and fails when the committed copy has drifted.
#
#   check-script-wiring.sh           # gate mode
#   check-script-wiring.sh --write   # regenerate scripts/README.md
set -uo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
cd "$REPO_ROOT" || exit 1
python3 - "${1:-check}" <<'PY'
import glob, os, re, sys

MODE = sys.argv[1].lstrip("-")

# Manual tools with no automated caller. Every entry carries its reason; a
# stale entry (the script gained a caller, or vanished) fails the gate.
ALLOWLIST = {}

SKIP_DIRS = (".venv", "__pycache__")
scripts = sorted(
    p for p in glob.glob("scripts/**/*", recursive=True)
    if os.path.isfile(p)
    and not any(d in p for d in SKIP_DIRS)
    and os.path.basename(p) != "README.md"
    and not p.endswith((".pyc", ".txt", ".json"))
)

corpus = {}
for pat in ["justfile", ".github/workflows/*.yml", ".github/actions/**/*.yml",
            ".claude/settings.json", "scripts/**/*", "e2e/**/*.ts", "e2e/*.json",
            "mix.exs", "apps/core/mix.exs", ".mcp.json"]:
    for f in glob.glob(pat, recursive=True):
        # The generated inventory names every script — it is the OUTPUT of this
        # gate, never a caller, or the first --write makes everything "wired".
        if f == "scripts/README.md": continue
        if os.path.isfile(f) and not any(d in f for d in SKIP_DIRS):
            try: corpus[f] = open(f, encoding="utf-8", errors="ignore").read()
            except OSError: pass

def callers(path):
    base = os.path.basename(path)
    # Python modules are imported by stem, not filename.
    needles = {base}
    if base.endswith(".py"):
        needles.add(base[:-3])
    found = []
    for f, txt in corpus.items():
        if f == path: continue
        if any(n in txt for n in needles):
            found.append(f)
    return sorted(found)

def purpose(path):
    try: lines = open(path, encoding="utf-8", errors="ignore").read().split("\n")
    except OSError: return ""
    for ln in lines[:12]:
        s = ln.strip()
        if s.startswith("#!") or not s: continue
        if s.startswith("#"): return s.lstrip("# ").strip()
        m = re.match(r'^\s*"""(.+?)("""|$)', ln)
        if m: return m.group(1).strip()
        break
    return ""

rows, orphans = [], []
for p in scripts:
    c = callers(p)
    if not c and p not in ALLOWLIST:
        orphans.append(p)
    rows.append((p, c, ALLOWLIST.get(p)))

stale = sorted(k for k in ALLOWLIST if k not in scripts or callers(k))

def render():
    out = ["# scripts/ — generated inventory",
           "",
           "<!-- GENERATED by check-script-wiring.sh --write — do not edit by hand. -->",
           "",
           "Every script here is either invoked by the listed callers or allowlisted as",
           "a manual tool with a reason. The wiring gate regenerates this file and fails",
           "on drift, so a script with no caller cannot sit here silently.",
           "",
           "| script | called by | purpose |",
           "|---|---|---|"]
    for p, c, allow in rows:
        if allow: who = f"_manual: {allow}_"
        elif c:   who = ", ".join(f"`{x}`" for x in c[:4]) + (" …" if len(c) > 4 else "")
        else:     who = "⚠️ none"
        out.append(f"| `{p}` | {who} | {purpose(p)[:96]} |")
    return "\n".join(out) + "\n"

if MODE == "write":
    open("scripts/README.md", "w").write(render())
    print(f"scripts/README.md written — {len(rows)} script(s)")
    sys.exit(0)

failed = False
if orphans:
    failed = True
    print(f"FAIL: {len(orphans)} script(s) with NO caller and no allowlist reason:", file=sys.stderr)
    for p in orphans: print(f"  {p}", file=sys.stderr)
    print("\nWire it, delete it, or allowlist it with the reason it is manual.", file=sys.stderr)
if stale:
    failed = True
    print(f"FAIL: {len(stale)} stale ALLOWLIST entr(y/ies) — gained a caller or vanished:", file=sys.stderr)
    for p in stale: print(f"  {p}", file=sys.stderr)
try: committed = open("scripts/README.md", encoding="utf-8").read()
except OSError: committed = None
if committed != render():
    failed = True
    print("FAIL: scripts/README.md is stale — run scripts/check-script-wiring.sh --write", file=sys.stderr)
if not failed:
    print(f"OK: {len(rows)} script(s) all wired or allowlisted; inventory current.")
sys.exit(1 if failed else 0)
PY
