# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/feedback.proto (FeedbackEntry)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.FeedbackEntries20260818153117 do
  use Ecto.Migration

  # `CREATE INDEX CONCURRENTLY` cannot run inside a transaction, so opt
  # out of Ecto's default migration-wide transaction.
  @disable_ddl_transaction true

  # Ecto holds its advisory migration lock on a separate idle connection
  # for the full CONCURRENTLY build. Neon's managed Postgres drops idle
  # TCP sockets on its own keepalive window, surfacing as a 300s hang +
  # `ssl send: closed` on fresh envs (observed 2026-04-22 bootstrapping
  # the staging project). Disabling the lock prevents that; deploys are
  # already serialised by the release pipeline.
  @disable_migration_lock true

  def up do
    create table(:feedback_entries, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :user_id, references(:users, type: :binary_id, prefix: "op", on_delete: :delete_all),
        null: false

      add :body, :text, null: false
      add :page_context, :text
      add :created_at, :utc_datetime_usec, null: false, default: fragment("NOW()")
    end

    create index(:feedback_entries, [desc: :created_at],
             prefix: "op",
             name: "feedback_entries_created_at_index",
             concurrently: true
           )

    create index(:feedback_entries, [:user_id],
             prefix: "op",
             name: "feedback_entries_user_id_index",
             concurrently: true
           )
  end

  def down do
    drop table(:feedback_entries, prefix: "op")
  end
end
