# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (ThirdSpace)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddLatitudeLongitudeNearestBookshopKmToThirdSpaces20260728131941 do
  use Ecto.Migration

  def up do
    alter table(:third_spaces, prefix: "op") do
      add :latitude, :float
      add :longitude, :float
      add :nearest_bookshop_km, :float
    end
  end

  def down do
    alter table(:third_spaces, prefix: "op") do
      remove :latitude
      remove :longitude
      remove :nearest_bookshop_km
    end
  end
end
