# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/internal/v1/audit.proto (AuditEntry)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddEndpointLatencyMsSuccessRowCountOperatorSessionIdToAuditLog20260504182149 do
  use Ecto.Migration

  def up do
    alter table(:audit_log, prefix: "audit") do
      add :endpoint, :text
      add :latency_ms, :integer
      add :success, :boolean
      add :row_count, :integer
      add :operator_session_id, :string
    end
  end

  def down do
    alter table(:audit_log, prefix: "audit") do
      remove :endpoint
      remove :latency_ms
      remove :success
      remove :row_count
      remove :operator_session_id
    end
  end
end
