# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (PriceSnapshot)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddBookEditionIdToPriceSnapshots20260727204630 do
  use Ecto.Migration

  def up do
    alter table(:price_snapshots, prefix: "op") do
      add :book_edition_id, :binary_id, null: false
    end
  end

  def down do
    alter table(:price_snapshots, prefix: "op") do
      remove :book_edition_id
    end
  end
end
