# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/upload.proto (UploadedImage)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddUserIdToUploadedImages20260401074249 do
  use Ecto.Migration

  def up do
    alter table(:uploaded_images, prefix: "op") do
      add_if_not_exists :user_id, :binary_id
    end
  end

  def down do
    alter table(:uploaded_images, prefix: "op") do
      remove :user_id
    end
  end
end
