# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/user.proto (User)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddSyndicationDefaultToUsers20260810084923 do
  use Ecto.Migration

  def up do
    alter table(:users, prefix: "op") do
      add :syndication_default, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:users, prefix: "op") do
      remove :syndication_default
    end
  end
end
