# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (Bookstore)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddUnscrapableReasonToBookstores20260728122253 do
  use Ecto.Migration

  def up do
    alter table(:bookstores, prefix: "op") do
      add :unscrapable_reason, :text
    end
  end

  def down do
    alter table(:bookstores, prefix: "op") do
      remove :unscrapable_reason
    end
  end
end
