# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/import.proto (LibraryImport)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.LibraryImports20260810075145 do
  use Ecto.Migration

  @disable_ddl_transaction true

  @disable_migration_lock true

  def up do
    create table(:library_imports, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :user_id, references(:users, type: :binary_id, prefix: "op", on_delete: :delete_all),
        null: false

      add :source, :text, null: false, default: "goodreads"
      add :filename, :text
      add :status, :text, null: false, default: "enqueued"
      add :row_count, :integer, null: false, default: 0
      add :processed_count, :integer, null: false, default: 0
      add :shelved_count, :integer, null: false, default: 0
      add :duplicate_count, :integer, null: false, default: 0
      add :unverified_count, :integer, null: false, default: 0
      add :unreadable_count, :integer, null: false, default: 0
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec

      timestamps(type: :utc_datetime_usec)
    end

    create index(:library_imports, [:user_id], prefix: "op", concurrently: true)

    create index(:library_imports, [:user_id, desc: :created_at],
             prefix: "op",
             name: "library_imports_user_id_created_at_index",
             concurrently: true
           )

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.library_imports TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.library_imports FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:library_imports, prefix: "op")
  end
end
