# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (Bookstore)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddEventsPageEtagEventsPageLastModifiedToBookstores20260729131125 do
  use Ecto.Migration

  def up do
    alter table(:bookstores, prefix: "op") do
      add :events_page_etag, :text
      add :events_page_last_modified, :text
    end
  end

  def down do
    alter table(:bookstores, prefix: "op") do
      remove :events_page_etag
      remove :events_page_last_modified
    end
  end
end
