# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/user.proto (User)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddPendingEmailPendingEmailTokenPendingEmailSentAtPendingEmailRevertTokenToUsers20260819041556 do
  use Ecto.Migration

  def up do
    alter table(:users, prefix: "op") do
      add :pending_email, :text
      add :pending_email_token, :text
      add :pending_email_sent_at, :utc_datetime_usec
      add :pending_email_revert_token, :text
    end
  end

  def down do
    alter table(:users, prefix: "op") do
      remove :pending_email
      remove :pending_email_token
      remove :pending_email_sent_at
      remove :pending_email_revert_token
    end
  end
end
