# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/infra/v1/feed_cache.proto (FeedCacheEntry)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.FeedCache20260720152621 do
  use Ecto.Migration

  # `CREATE INDEX CONCURRENTLY` cannot run inside a transaction, so opt
  # out of Ecto's default migration-wide transaction.
  @disable_ddl_transaction true

  # Ecto holds its advisory migration lock on a separate idle connection
  # for the full CONCURRENTLY build. Neon's managed Postgres drops idle
  # TCP sockets on its own keepalive window, surfacing as a 300s hang +
  # `ssl send: closed` on fresh envs (observed 2026-04-22 bootstrapping
  # the staging project). Disabling the lock prevents that; deploys are
  # already serialised by the release pipeline.
  @disable_migration_lock true

  def up do
    create table(:feed_cache, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true
      add :bookshelf_id, references(:bookshelves, type: :binary_id, prefix: "op", on_delete: :delete_all), null: false
      add :atom_xml, :text, null: false
      add :etag, :text, null: false

      timestamps(type: :utc_datetime_usec)
    end

    create index(:feed_cache, [:bookshelf_id], prefix: "op", concurrently: true)
    create unique_index(:feed_cache, [:bookshelf_id], prefix: "op", name: "feed_cache_bookshelf_id_unique_index", concurrently: true)
  end

  def down do
    drop table(:feed_cache, prefix: "op")
  end
end
