# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/writing_assistant.proto (TurnFeedback)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.TurnFeedback20260713181719 do
  use Ecto.Migration

  @disable_ddl_transaction true

  @disable_migration_lock true

  def up do
    create table(:turn_feedback, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :session_id,
          references(:blog_assistant_sessions,
            type: :binary_id,
            prefix: "op",
            on_delete: :delete_all
          ),
          null: false

      add :turn_index, :integer, null: false
      add :rating, :text
      add :comment, :text

      timestamps(type: :utc_datetime_usec, updated_at: false)
    end

    create index(:turn_feedback, [:session_id], prefix: "op", concurrently: true)

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.turn_feedback TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.turn_feedback FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:turn_feedback, prefix: "op")
  end
end
