# Generated by mix proto.sync, then manually enhanced for constraints.
# Source: stacks/internal/v1/partner.proto (Partner)
defmodule Core.Repo.Migrations.Partners20260330035921 do
  use Ecto.Migration

  def change do
    create table(:partners, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :name, :text, null: false
      add :business_type, :text, null: false
      add :contact_email, :text, null: false
      add :website_url, :text
      add :status, :text, null: false, default: "pending"
      add :hmac_secret, :text
      add :api_key_prefix, :text

      add :approved_by_id,
          references(:users, type: :binary_id, prefix: "op", on_delete: :nilify_all)

      add :approved_at, :utc_datetime_usec

      timestamps(type: :utc_datetime_usec)
    end

    create unique_index(:partners, [:contact_email], prefix: "op")
    create index(:partners, [:status], prefix: "op")
    create index(:partners, [:approved_by_id], prefix: "op")

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.partners TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.partners FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end
end
