# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/import.proto (LibraryImportRow)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.LibraryImportRows20260810075145 do
  use Ecto.Migration

  # `CREATE INDEX CONCURRENTLY` cannot run inside a transaction, so opt
  # out of Ecto's default migration-wide transaction.
  @disable_ddl_transaction true

  # Ecto holds its advisory migration lock on a separate idle connection
  # for the full CONCURRENTLY build. Neon's managed Postgres drops idle
  # TCP sockets on its own keepalive window, surfacing as a 300s hang +
  # `ssl send: closed` on fresh envs (observed 2026-04-22 bootstrapping
  # the staging project). Disabling the lock prevents that; deploys are
  # already serialised by the release pipeline.
  @disable_migration_lock true

  def up do
    create table(:library_import_rows, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :import_id,
          references(:library_imports, type: :binary_id, prefix: "op", on_delete: :delete_all),
          null: false

      add :row_number, :integer, null: false
      add :raw_title, :text
      add :raw_author, :text
      add :raw_isbn, :text
      add :raw_isbn13, :text
      add :goodreads_shelf, :text
      add :raw_rating, :integer, null: false, default: 0
      add :raw_review, :text
      add :raw_notes, :text
      add :raw_binding, :text
      add :raw_date_read, :text
      add :raw_date_added, :text
      add :raw_read_count, :integer, null: false, default: 0
      add :raw_owned_copies, :integer, null: false, default: 0
      add :outcome, :text
      add :reason, :text
      add :book_id, references(:books, type: :binary_id, prefix: "op", on_delete: :nilify_all)

      add :placement_id,
          references(:bookshelf_placements,
            type: :binary_id,
            prefix: "op",
            on_delete: :nilify_all
          )

      add :created_at, :utc_datetime_usec
    end

    create index(:library_import_rows, [:book_id], prefix: "op", concurrently: true)
    create index(:library_import_rows, [:import_id], prefix: "op", concurrently: true)
    create index(:library_import_rows, [:placement_id], prefix: "op", concurrently: true)

    create unique_index(:library_import_rows, [:import_id, :row_number],
             prefix: "op",
             name: "library_import_rows_import_id_row_number_index",
             concurrently: true
           )

    create index(:library_import_rows, [:import_id, :outcome],
             prefix: "op",
             name: "library_import_rows_import_id_outcome_index",
             concurrently: true
           )
  end

  def down do
    drop table(:library_import_rows, prefix: "op")
  end
end
