# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/user.proto (User)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddFailedLoginCountFailedLoginFirstAtLockedUntilToUsers20260520060959 do
  use Ecto.Migration

  def up do
    alter table(:users, prefix: "op") do
      add :failed_login_count, :integer, null: false, default: 0
      add :failed_login_first_at, :utc_datetime_usec
      add :locked_until, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users, prefix: "op") do
      remove :failed_login_count
      remove :failed_login_first_at
      remove :locked_until
    end
  end
end
