# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/infra/v1/book_cache.proto (TitleSearchCacheEntry)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.TitleSearchCache20260422072906 do
  use Ecto.Migration

  @disable_ddl_transaction true

  @disable_migration_lock true

  def up do
    create table(:title_search_cache, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true
      add :cache_key, :text, null: false
      add :title, :text
      add :author, :text
      add :raw_text, :text
      add :outcome, :text, null: false
      add :isbn, :text
      add :metadata, :map
      add :expires_at, :utc_datetime_usec, null: false

      timestamps(type: :utc_datetime_usec)
    end

    create unique_index(:title_search_cache, [:cache_key], prefix: "op", concurrently: true)

    create index(:title_search_cache, [:expires_at],
             prefix: "op",
             name: "title_search_cache_expires_at_index",
             concurrently: true
           )

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.title_search_cache TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.title_search_cache FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:title_search_cache, prefix: "op")
  end
end
