# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/writing_assistant.proto (UserBookContentAccess)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.UserBookContentAccess20260713181721 do
  use Ecto.Migration

  @disable_ddl_transaction true

  @disable_migration_lock true

  def up do
    create table(:user_book_content_access, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :user_id, references(:users, type: :binary_id, prefix: "op", on_delete: :delete_all),
        null: false

      add :book_id, references(:books, type: :binary_id, prefix: "op", on_delete: :delete_all),
        null: false

      add :access_type, :text, null: false, default: "granted"
      add :granted_at, :utc_datetime_usec

      timestamps(type: :utc_datetime_usec, updated_at: false)
    end

    create index(:user_book_content_access, [:book_id], prefix: "op", concurrently: true)
    create index(:user_book_content_access, [:user_id], prefix: "op", concurrently: true)

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.user_book_content_access TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.user_book_content_access FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:user_book_content_access, prefix: "op")
  end
end
