# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/book.proto (Edition)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddVerificationSourceToBookEditions20260730193134 do
  use Ecto.Migration

  def up do
    alter table(:book_editions, prefix: "op") do
      add :verification_source, :text
    end
  end

  def down do
    alter table(:book_editions, prefix: "op") do
      remove :verification_source
    end
  end
end
