# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/blog.proto (PostSyndication)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.PostSyndications20260810084923 do
  use Ecto.Migration

  @disable_ddl_transaction true

  @disable_migration_lock true

  def up do
    create table(:post_syndications, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :post_id,
          references(:blog_posts, type: :binary_id, prefix: "op", on_delete: :delete_all),
          null: false

      add :target, :text, null: false, default: "substack"
      add :method, :text, null: false
      add :canonical_url, :text, null: false
      add :syndicated_url, :text

      timestamps(type: :utc_datetime_usec, updated_at: false)
    end

    create index(:post_syndications, [:post_id], prefix: "op", concurrently: true)

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.post_syndications TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.post_syndications FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:post_syndications, prefix: "op")
  end
end
