# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (Bookstore)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddPriceSourceIsbnLocationLookupModeCapabilityProbedAtCanaryIsbnRobotsBlockedPathToBookstores20260728071143 do
  use Ecto.Migration

  def up do
    alter table(:bookstores, prefix: "op") do
      add :price_source, :text
      add :isbn_location, :text
      add :lookup_mode, :text
      add :capability_probed_at, :utc_datetime_usec
      add :canary_isbn, :text
      add :robots_blocked_path, :text
    end
  end

  def down do
    alter table(:bookstores, prefix: "op") do
      remove :price_source
      remove :isbn_location
      remove :lookup_mode
      remove :capability_probed_at
      remove :canary_isbn
      remove :robots_blocked_path
    end
  end
end
