# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (ThirdSpaceEvent)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddEndsAtToThirdSpaceEvents20260330094620 do
  use Ecto.Migration

  def up do
    alter table(:third_space_events, prefix: "op") do
      add :ends_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:third_space_events, prefix: "op") do
      remove :ends_at
    end
  end
end
