# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/user.proto (User)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddConsentWritingAssistantConsentWritingAssistantAtToUsers20260713201728 do
  use Ecto.Migration

  def up do
    alter table(:users, prefix: "op") do
      add :consent_writing_assistant, :boolean, default: false
      add :consent_writing_assistant_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users, prefix: "op") do
      remove :consent_writing_assistant
      remove :consent_writing_assistant_at
    end
  end
end
