# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/user.proto (InviteCode)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.InviteCodes20260809212326 do
  use Ecto.Migration

  @disable_ddl_transaction true

  @disable_migration_lock true

  def up do
    create table(:invite_codes, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true
      add :code_hash, :text, null: false
      add :code_prefix, :text, null: false

      add :issued_by_id,
          references(:users, type: :binary_id, prefix: "op", on_delete: :nilify_all)

      add :note, :text
      add :invited_email, :text
      add :max_uses, :integer, null: false, default: 1
      add :use_count, :integer, null: false, default: 0
      add :expires_at, :utc_datetime_usec

      add :redeemed_by_id,
          references(:users, type: :binary_id, prefix: "op", on_delete: :nilify_all)

      add :redeemed_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      timestamps(type: :utc_datetime_usec)
    end

    create index(:invite_codes, [:issued_by_id], prefix: "op", concurrently: true)
    create index(:invite_codes, [:redeemed_by_id], prefix: "op", concurrently: true)

    create unique_index(:invite_codes, [:code_hash],
             prefix: "op",
             name: "invite_codes_code_hash_index",
             concurrently: true
           )

    create index(:invite_codes, [desc: :created_at],
             prefix: "op",
             name: "invite_codes_created_at_index",
             concurrently: true
           )

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.invite_codes TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.invite_codes FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:invite_codes, prefix: "op")
  end
end
