# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/blog.proto (BlogPost)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddSyndicatedToBlogPosts20260810084923 do
  use Ecto.Migration

  def up do
    alter table(:blog_posts, prefix: "op") do
      add :syndicated, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:blog_posts, prefix: "op") do
      remove :syndicated
    end
  end
end
