# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
#
# Timestamp bumped 131941 → 131942 by hand: proto.sync emitted this and the
# third_spaces migration in the same second, and Ecto rejects duplicate versions.
# Source: stacks/common/v1/enrichment.proto (Bookstore)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddLatitudeLongitudeToBookstores20260728131942 do
  use Ecto.Migration

  def up do
    alter table(:bookstores, prefix: "op") do
      add :latitude, :float
      add :longitude, :float
    end
  end

  def down do
    alter table(:bookstores, prefix: "op") do
      remove :latitude
      remove :longitude
    end
  end
end
