# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/writing_assistant.proto (RetrievalLog)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.RetrievalLog20260713181720 do
  use Ecto.Migration

  @disable_ddl_transaction true

  @disable_migration_lock true

  def up do
    create table(:retrieval_log, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :session_id,
          references(:blog_assistant_sessions,
            type: :binary_id,
            prefix: "op",
            on_delete: :delete_all
          ),
          null: false

      add :query, :text
      add :retrieved_ids, {:array, :binary_id}, default: []
      add :scores, {:array, :float}, default: []
      add :turn_index, :integer

      timestamps(type: :utc_datetime_usec, updated_at: false)
    end

    create index(:retrieval_log, [:session_id], prefix: "op", concurrently: true)

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.retrieval_log TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.retrieval_log FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:retrieval_log, prefix: "op")
  end
end
