# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/placement.proto (Placement)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddBookEditionIdToBookshelfPlacements20260730193135 do
  use Ecto.Migration

  def up do
    alter table(:bookshelf_placements, prefix: "op") do
      add :book_edition_id,
          references(:book_editions, type: :binary_id, prefix: "op", on_delete: :nilify_all)
    end
  end

  def down do
    alter table(:bookshelf_placements, prefix: "op") do
      remove :book_edition_id
    end
  end
end
