# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/user.proto (User)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddLockoutDurationSecondsToUsers20260819043038 do
  use Ecto.Migration

  def up do
    alter table(:users, prefix: "op") do
      add :lockout_duration_seconds, :integer
    end
  end

  def down do
    alter table(:users, prefix: "op") do
      remove :lockout_duration_seconds
    end
  end
end
