# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (ThirdSpace)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddCuratedCuratedNoteToThirdSpaces20260728142154 do
  use Ecto.Migration

  def up do
    alter table(:third_spaces, prefix: "op") do
      add :curated, :boolean
      add :curated_note, :text
    end
  end

  def down do
    alter table(:third_spaces, prefix: "op") do
      remove :curated
      remove :curated_note
    end
  end
end
