# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/placement.proto (Placement)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddSourceToBookshelfPlacements20260810075145 do
  use Ecto.Migration

  def up do
    alter table(:bookshelf_placements, prefix: "op") do
      add :source, :text, null: false, default: "manual"
    end
  end

  def down do
    alter table(:bookshelf_placements, prefix: "op") do
      remove :source
    end
  end
end
