# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (DiscoveredSource)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddExclusionRequestedAtToDiscoveredSources20260728103335 do
  use Ecto.Migration

  def up do
    alter table(:discovered_sources, prefix: "op") do
      add :exclusion_requested_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:discovered_sources, prefix: "op") do
      remove :exclusion_requested_at
    end
  end
end
