# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/writing_assistant.proto (BlogAssistantSession)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.BlogAssistantSessions20260713181718 do
  use Ecto.Migration

  @disable_ddl_transaction true

  @disable_migration_lock true

  def up do
    create table(:blog_assistant_sessions, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :user_id, references(:users, type: :binary_id, prefix: "op", on_delete: :delete_all),
        null: false

      add :status, :text, null: false, default: "active"
      add :topic, :text
      add :model, :text
      add :started_at, :utc_datetime_usec

      timestamps(type: :utc_datetime_usec)
    end

    create index(:blog_assistant_sessions, [:user_id], prefix: "op", concurrently: true)

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.blog_assistant_sessions TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.blog_assistant_sessions FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:blog_assistant_sessions, prefix: "op")
  end
end
