# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/blog.proto (PostComment)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.PostComments20260329212333 do
  use Ecto.Migration

  def up do
    create table(:post_comments, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true

      add :post_id,
          references(:blog_posts, type: :binary_id, prefix: "op", on_delete: :delete_all),
          null: false

      add :author_id, references(:users, type: :binary_id, prefix: "op", on_delete: :nilify_all)
      add :parent_id, :binary_id
      add :body, :text
      add :created_at, :utc_datetime_usec, default: fragment("NOW()")
    end

    create index(:post_comments, [:author_id], prefix: "op")
    create index(:post_comments, [:post_id], prefix: "op")

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.post_comments TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.post_comments FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:post_comments, prefix: "op")
  end
end
