# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/user.proto (User)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddHandleToUsers20260714200119 do
  use Ecto.Migration

  def up do
    alter table(:users, prefix: "op") do
      add :handle, :text
    end
  end

  def down do
    alter table(:users, prefix: "op") do
      remove :handle
    end
  end
end
