# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (Bookstore)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddEventsPathEventsPathCheckedAtEventsUnresolvedReasonToBookstores20260729125329 do
  use Ecto.Migration

  def up do
    alter table(:bookstores, prefix: "op") do
      add :events_path, :text
      add :events_path_checked_at, :utc_datetime_usec
      add :events_unresolved_reason, :text
    end
  end

  def down do
    alter table(:bookstores, prefix: "op") do
      remove :events_path
      remove :events_path_checked_at
      remove :events_unresolved_reason
    end
  end
end
