# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/infra/v1/book_cache.proto (IsbnResolverCacheEntry)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.IsbnResolverCache20260422072905 do
  use Ecto.Migration

  # `CREATE INDEX CONCURRENTLY` cannot run inside a transaction, so opt
  # out of Ecto's default migration-wide transaction. The migration lock
  # is still held (on a separate connection) so concurrent migrator runs
  # remain serialised.
  @disable_ddl_transaction true

  def up do
    create table(:isbn_resolver_cache, prefix: "op", primary_key: false) do
      add :id, :binary_id, primary_key: true
      add :isbn, :text, null: false
      add :outcome, :text, null: false
      add :metadata, :map
      add :expires_at, :utc_datetime_usec, null: false

      timestamps(type: :utc_datetime_usec)
    end

    create unique_index(:isbn_resolver_cache, [:isbn], prefix: "op", concurrently: true)

    create index(:isbn_resolver_cache, [:expires_at],
             prefix: "op",
             name: "isbn_resolver_cache_expires_at_index",
             concurrently: true
           )

    execute(
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          GRANT SELECT ON op.isbn_resolver_cache TO stacks_dbt;
        END IF;
      END $$;
      """,
      """
      DO $$ BEGIN
        IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'stacks_dbt') THEN
          REVOKE SELECT ON op.isbn_resolver_cache FROM stacks_dbt;
        END IF;
      END $$;
      """
    )
  end

  def down do
    drop table(:isbn_resolver_cache, prefix: "op")
  end
end
