# Generated by mix proto.sync — DO NOT EDIT MANUALLY.
# Source: stacks/common/v1/enrichment.proto (Bookstore)
# Regenerate: mix proto.sync
defmodule Core.Repo.Migrations.AddRobotsBlockedRuleRobotsBlockedAtToBookstores20260728120914 do
  use Ecto.Migration

  def up do
    alter table(:bookstores, prefix: "op") do
      add :robots_blocked_rule, :text
      add :robots_blocked_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:bookstores, prefix: "op") do
      remove :robots_blocked_rule
      remove :robots_blocked_at
    end
  end
end
