defmodule Stacks.Feeds do
  @moduledoc """
      Context for generating Atom 1.0 feeds for public bookshelves.

      Each platform-visible bookshelf can have an Atom feed that RSS readers can
      subscribe to. Feeds are regenerated by `RegenerateFeedJob` when placement
      events fire, and served by `FeedController` with ETag caching.
  """

  import Ecto.Query, only: [from: 2]

  alias Core.Repo
  alias Stacks.Feeds.FeedCacheEntry
  alias Stacks.Shelving
  alias Stacks.Shelving.PlacementHistory
  alias Stacks.Visibility

  require Logger

  @atom_ns "http://www.w3.org/2005/Atom"

  @doc """
      Computes an ETag string from XML content.

      Uses MD5 hashing, hex-encoded in lowercase.
  """
  @spec compute_etag(String.t()) :: String.t()
  def compute_etag(xml) when is_binary(xml) do
    :crypto.hash(:md5, xml) |> Base.encode16(case: :lower)
  end

  @doc """
      Cache-first fetch for `FeedController`: resolve the platform-visible
      bookshelf, serve the `op.feed_cache` row on a hit; on a miss generate,
      synchronously fill the cache, and serve. The etag is the pure MD5 of the
      XML, so 304s hold across hit and miss-fill. The cache is an optimisation,
      not a correctness dependency — a failed miss-fill write logs and still
      serves the fresh XML. `{:ok, xml, etag}` or
      `{:error,:not_found |:not_public}`.
  """
  @spec fetch_feed(binary(), String.t(), map() | nil) ::
          {:ok, String.t(), String.t()} | {:error, :not_found | :not_public}
  def fetch_feed(user_id, bookshelf_name, viewer \\ nil) do
    with {:ok, bookshelf} <- resolve_shared_bookshelf(user_id, bookshelf_name),
         :ok <- authorize_viewer(bookshelf, viewer) do
      case get_cached(bookshelf.id) do
        {:ok, xml, etag} -> {:ok, xml, etag}
        :miss -> render_and_serve(bookshelf)
      end
    end
  end

  @doc """
      Regenerates a bookshelf's feed and upserts `op.feed_cache` (used by
      `RegenerateFeedJob`). Idempotent — the etag is a pure function of the XML.
      Unlike the read path, filling the cache IS the job: a failed write returns
      `{:error, {:cache_write_failed, changeset}}` so the worker retries instead
      of silently dropping the update. Non-public/missing bookshelves return
      `{:error,:not_public |:not_found}` for skip/cancel.
  """
  @spec regenerate(binary(), String.t()) ::
          {:ok, String.t(), String.t()}
          | {:error, :not_found | :not_public | {:cache_write_failed, Ecto.Changeset.t()}}
  def regenerate(user_id, bookshelf_name) do
    with {:ok, bookshelf} <- resolve_shared_bookshelf(user_id, bookshelf_name) do
      {xml, etag} = render_feed(bookshelf)

      case cache_writer().(bookshelf.id, xml, etag) do
        {:ok, _entry} -> {:ok, xml, etag}
        {:error, changeset} -> {:error, {:cache_write_failed, changeset}}
      end
    end
  end

  @doc """
      Reads the persisted feed for a bookshelf id.

      Returns `{:ok, xml, etag}` on a hit or `:miss` when no row exists.
  """
  @spec get_cached(binary()) :: {:ok, String.t(), String.t()} | :miss
  def get_cached(bookshelf_id) do
    case Repo.get_by(FeedCacheEntry, bookshelf_id: bookshelf_id) do
      nil -> :miss
      %FeedCacheEntry{atom_xml: xml, etag: etag} -> {:ok, xml, etag}
    end
  end

  @doc """
      Upserts the `op.feed_cache` row for a bookshelf (one row per bookshelf).

      Conflicts on the unique `bookshelf_id` index replace the XML, etag, and
      `updated_at` only. The changeset declares the `bookshelf_id` foreign-key
      constraint, so a missing parent bookshelf (e.g. deleted between resolve and
      write) returns `{:error, changeset}` rather than raising `Ecto.ConstraintError`.

      Returns `{:ok, entry}` or `{:error, changeset}`.
  """
  @spec put_cache(binary(), String.t(), String.t()) ::
          {:ok, FeedCacheEntry.t()} | {:error, Ecto.Changeset.t()}
  def put_cache(bookshelf_id, xml, etag) do
    %FeedCacheEntry{}
    |> Ecto.Changeset.change(bookshelf_id: bookshelf_id, atom_xml: xml, etag: etag)
    |> Ecto.Changeset.foreign_key_constraint(:bookshelf_id)
    |> Repo.insert(
      on_conflict: {:replace, [:atom_xml, :etag, :updated_at]},
      conflict_target: :bookshelf_id
    )
  end

  @doc """
      Does a bookshelf at this visibility have an Atom feed? The SINGLE source
      of truth: this module decides whether to serve the feed and
      `ProtoJSON.public_profile/2` whether to offer the subscribe link — the two
      previously duplicated the rule ("mirrors exactly" by comment, i.e. not
      maintained) and would have diverged on the first ladder change. One
      function makes the mirror structural.
  """
  @spec feed_eligible?(String.t()) :: boolean()
  def feed_eligible?(visibility), do: Visibility.at_least?(visibility, "platform")

  @doc """
      Must the requester be signed in to read this bookshelf's feed?

      `platform` means "any authenticated platform user — **not** visible to logged-out" on the Audience
      ladder, so a `platform` bookshelf's feed requires a viewer. `public` means "anyone with the link,
      signed in or not", so it does not.

      ⚠️ Before this existed, the feed route sat in a wholly unauthenticated pipeline and served a
      `platform` bookshelf's contents — titles, authors, a reader's shelf — to any anonymous client.
      That contradicted the ladder the rest of the system enforces: `GET /api/u/:handle` already 404s a
      `platform` profile for a logged-out visitor. Owner decision 2026-07-29: `platform` requires
      auth, `public` does not.
  """
  @spec feed_requires_auth?(String.t()) :: boolean()
  def feed_requires_auth?(visibility), do: not Visibility.at_least?(visibility, "public")

  defp authorize_viewer(%{visibility: visibility}, viewer) do
    if feed_requires_auth?(visibility) and is_nil(viewer) do
      {:error, :not_found}
    else
      :ok
    end
  end

  defp resolve_shared_bookshelf(user_id, bookshelf_name) do
    case Shelving.get_bookshelf(user_id, bookshelf_name) do
      nil ->
        {:error, :not_found}

      %{visibility: visibility} = bookshelf ->
        if feed_eligible?(visibility),
          do: {:ok, bookshelf},
          else: {:error, :not_public}
    end
  end

  defp render_and_serve(bookshelf) do
    {xml, etag} = render_feed(bookshelf)

    case cache_writer().(bookshelf.id, xml, etag) do
      {:ok, _entry} ->
        :ok

      {:error, changeset} ->
        Logger.warning(
          "Feeds: feed_cache write failed for bookshelf=#{bookshelf.id}, serving fresh render: " <>
            inspect(changeset.errors)
        )
    end

    {:ok, xml, etag}
  end

  defp render_feed(bookshelf) do
    placements = Shelving.get_bookshelf_books(bookshelf.user_id, bookshelf.name)
    xml = build_atom_xml(bookshelf, placements, moved_book_ids(bookshelf, placements))
    etag = compute_etag(xml)
    {xml, etag}
  end

  @spec moved_book_ids(map(), list()) :: %{optional(binary()) => true}
  defp moved_book_ids(_bookshelf, []), do: %{}

  defp moved_book_ids(bookshelf, placements) do
    book_ids = Enum.map(placements, & &1.book_id)

    Repo.all(
      from h in PlacementHistory,
        where:
          h.book_id in ^book_ids and h.to_bookshelf == ^bookshelf.id and
            not is_nil(h.from_bookshelf),
        select: h.book_id,
        distinct: true
    )
    |> Map.new(&{&1, true})
  end

  defp cache_writer do
    Application.get_env(:core, :feed_cache_writer, &put_cache/3)
  end

  defp build_atom_xml(bookshelf, placements, moved_ids) do
    display_name = feed_display_name(bookshelf.user)

    updated =
      placements
      |> Enum.map(& &1.placed_at)
      |> Enum.reject(&is_nil/1)
      |> Enum.max(DateTime, fn -> DateTime.utc_now() end)
      |> DateTime.to_iso8601()

    entries = Enum.map_join(placements, "\n", &build_entry(&1, bookshelf.name, moved_ids))

    """
    <?xml version="1.0" encoding="utf-8"?>
    <feed xmlns="#{@atom_ns}">
      <title>#{escape_xml(display_name)}'s #{humanize_bookshelf(bookshelf.name)}</title>
      <id>urn:stacks:feed:#{bookshelf.id}</id>
      <updated>#{updated}</updated>
      <author>
        <name>#{escape_xml(display_name)}</name>
      </author>
    #{entries}
    </feed>
    """
    |> String.trim()
  end

  defp build_entry(placement, bookshelf_name, moved_ids) do
    book = placement.book
    title = if book, do: book.title, else: "Unknown Book"

    author_name =
      if book && book.author,
        do: book.author.name,
        else: "Unknown Author"

    isbn = primary_isbn(book)

    placed_at =
      if placement.placed_at,
        do: DateTime.to_iso8601(placement.placed_at),
        else: DateTime.to_iso8601(DateTime.utc_now())

    verb = if Map.has_key?(moved_ids, placement.book_id), do: "moved", else: "added"

    summary =
      "#{escape_xml(title)} by #{escape_xml(author_name)} #{verb} to " <>
        "#{humanize_bookshelf(bookshelf_name)}"

    """
      <entry>
        <title>#{escape_xml(title)}</title>
        <id>urn:stacks:placement:#{placement.id}</id>
        <updated>#{placed_at}</updated>
        <summary>#{summary}</summary>
        <author>
          <name>#{escape_xml(author_name)}</name>
        </author>#{cover_link(placement.book)}#{isbn_link(isbn)}
      </entry>\
    """
  end

  defp cover_link(nil), do: ""

  defp cover_link(book) do
    book
    |> primary_cover_url()
    |> case do
      nil ->
        ""

      url ->
        "\n    <link rel=\"enclosure\" type=\"image/jpeg\" href=\"#{escape_xml(url)}\" />"
    end
  end

  defp primary_cover_url(%{editions: editions}) when is_list(editions) do
    primary = Enum.find(editions, & &1.is_primary) || List.first(editions)
    primary && primary.cover_image_url
  end

  defp primary_cover_url(_book), do: nil

  defp primary_isbn(nil), do: nil

  defp primary_isbn(book) do
    case book.editions do
      editions when is_list(editions) ->
        primary = Enum.find(editions, &(&1.is_primary == true))
        if primary, do: primary.isbn, else: nil

      _ ->
        nil
    end
  end

  defp isbn_link(nil), do: ""

  defp isbn_link(isbn) do
    "\n    <link rel=\"related\" href=\"https://openlibrary.org/isbn/#{isbn}\" />"
  end

  defp feed_display_name(user) do
    cond do
      present?(user.display_name) -> user.display_name
      present?(user.handle) -> user.handle
      true -> "A Stacks reader"
    end
  end

  defp present?(nil), do: false
  defp present?(value) when is_binary(value), do: String.trim(value) != ""

  defp humanize_bookshelf(name) do
    name
    |> String.replace("_", " ")
    |> String.split(" ")
    |> Enum.map_join(" ", &String.capitalize/1)
  end

  defp escape_xml(nil), do: ""

  defp escape_xml(text) do
    text
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
    |> String.replace("'", "&apos;")
  end
end
