defmodule Stacks.Feeds do
  @moduledoc """
  Context for generating Atom 1.0 feeds for public bookshelves.

  Each platform-visible bookshelf can have an Atom feed that RSS readers can
  subscribe to. Feeds are regenerated by `RegenerateFeedJob` when placement
  events fire, and served by `FeedController` with ETag caching.
  """

  import Ecto.Query, only: [from: 2]

  alias Core.Repo
  alias Stacks.Feeds.FeedCacheEntry
  alias Stacks.Shelving
  alias Stacks.Shelving.PlacementHistory
  alias Stacks.Visibility

  require Logger

  @atom_ns "http://www.w3.org/2005/Atom"

  @doc """
  Computes an ETag string from XML content.

  Uses MD5 hashing, hex-encoded in lowercase.
  """
  @spec compute_etag(String.t()) :: String.t()
  def compute_etag(xml) when is_binary(xml) do
    :crypto.hash(:md5, xml) |> Base.encode16(case: :lower)
  end

  @doc """
  Cache-first fetch used by `FeedController`.

  Resolves the platform-visible bookshelf, then serves the persisted
  `op.feed_cache` row on a hit. On a miss it generates the feed, synchronously
  fills the cache (so the next read is a guaranteed hit), and serves the fresh
  result. Because the stored etag is the pure MD5 of the stored XML, a `304`
  holds identically across a cache hit and a miss-fill.

  The cache is an optimization, not a correctness dependency: if the miss-fill
  write fails, the freshly-rendered XML is still served (the failure is logged),
  so a public read never 500s on a cache-write error.

  Returns `{:ok, xml, etag}` or `{:error, :not_found | :not_public}`.
  """
  @spec fetch_feed(binary(), String.t()) ::
          {:ok, String.t(), String.t()} | {:error, :not_found | :not_public}
  def fetch_feed(user_id, bookshelf_name) do
    with {:ok, bookshelf} <- resolve_shared_bookshelf(user_id, bookshelf_name) do
      case get_cached(bookshelf.id) do
        {:ok, xml, etag} -> {:ok, xml, etag}
        :miss -> render_and_serve(bookshelf)
      end
    end
  end

  @doc """
  Regenerates the feed for a bookshelf and upserts the `op.feed_cache` row.

  Used by `RegenerateFeedJob` on a placement event. Idempotent: two runs over
  unchanged data leave a single row with the same etag (the etag is a pure
  function of the XML). Non-public / missing bookshelves write no row and
  surface `{:error, :not_public}` / `{:error, :not_found}` for the caller to
  translate into skip/cancel.

  Because filling the cache *is* the job here (unlike the read path), a failed
  cache write surfaces as `{:error, {:cache_write_failed, changeset}}` so the
  worker can retry rather than silently dropping the update.

  Returns `{:ok, xml, etag}` or
  `{:error, :not_found | :not_public | {:cache_write_failed, Ecto.Changeset.t()}}`.
  """
  @spec regenerate(binary(), String.t()) ::
          {:ok, String.t(), String.t()}
          | {:error, :not_found | :not_public | {:cache_write_failed, Ecto.Changeset.t()}}
  def regenerate(user_id, bookshelf_name) do
    with {:ok, bookshelf} <- resolve_shared_bookshelf(user_id, bookshelf_name) do
      {xml, etag} = render_feed(bookshelf)

      case cache_writer().(bookshelf.id, xml, etag) do
        {:ok, _entry} -> {:ok, xml, etag}
        {:error, changeset} -> {:error, {:cache_write_failed, changeset}}
      end
    end
  end

  @doc """
  Reads the persisted feed for a bookshelf id.

  Returns `{:ok, xml, etag}` on a hit or `:miss` when no row exists.
  """
  @spec get_cached(binary()) :: {:ok, String.t(), String.t()} | :miss
  def get_cached(bookshelf_id) do
    case Repo.get_by(FeedCacheEntry, bookshelf_id: bookshelf_id) do
      nil -> :miss
      %FeedCacheEntry{atom_xml: xml, etag: etag} -> {:ok, xml, etag}
    end
  end

  @doc """
  Upserts the `op.feed_cache` row for a bookshelf (one row per bookshelf).

  Conflicts on the unique `bookshelf_id` index replace the XML, etag, and
  `updated_at` only. The changeset declares the `bookshelf_id` foreign-key
  constraint, so a missing parent bookshelf (e.g. deleted between resolve and
  write) returns `{:error, changeset}` rather than raising `Ecto.ConstraintError`.

  Returns `{:ok, entry}` or `{:error, changeset}`.
  """
  @spec put_cache(binary(), String.t(), String.t()) ::
          {:ok, FeedCacheEntry.t()} | {:error, Ecto.Changeset.t()}
  def put_cache(bookshelf_id, xml, etag) do
    %FeedCacheEntry{}
    |> Ecto.Changeset.change(bookshelf_id: bookshelf_id, atom_xml: xml, etag: etag)
    |> Ecto.Changeset.foreign_key_constraint(:bookshelf_id)
    |> Repo.insert(
      on_conflict: {:replace, [:atom_xml, :etag, :updated_at]},
      conflict_target: :bookshelf_id
    )
  end

  @doc """
  Does a bookshelf at this visibility have an Atom feed?

  **The single source of truth for that question**, because two callers need it and they must not
  answer it differently: this module decides whether to *serve* the feed, and
  `StacksWeb.ProtoJSON.public_profile/2` decides whether to *offer a subscribe link*. If the two
  disagree in one direction a reader is shown a link that 403s; in the other, a working feed is
  never advertised.

  ⚠️ **They did disagree.** Both hardcoded `visibility == "platform"`, with a comment in
  `proto_json.ex` promising it "mirrors `Feeds.resolve_platform_bookshelf/2` exactly" — an
  invariant maintained by duplication and a comment, which is to say not maintained. Fixing the
  ladder bug in one place would silently have broken the pair. Calling one function makes the
  mirror structural.
  """
  @spec feed_eligible?(String.t()) :: boolean()
  def feed_eligible?(visibility), do: Visibility.at_least?(visibility, "platform")

  # ── Private helpers ────────────────────────────────────────────────────────

  # Feed eligibility is "shared at least as widely as `platform`", not "is exactly `platform`".
  #
  # ⛔ It used to be the latter (`visibility != "platform"`), which refused a feed to a bookshelf
  # on the **most** shared tier — `public` — while serving one for the *less* shared `platform`.
  # Exposure and function ran in opposite directions. The `:not_public` atom is what hid it: it
  # reads as correct at every call site, and both rejection tests only ever covered `owner` and
  # `group`, so the literally-public case was never exercised.
  #
  # `Visibility.at_least?/2` treats an unknown value as most-private, so a typo fails closed.
  defp resolve_shared_bookshelf(user_id, bookshelf_name) do
    case Shelving.get_bookshelf(user_id, bookshelf_name) do
      nil ->
        {:error, :not_found}

      %{visibility: visibility} = bookshelf ->
        if feed_eligible?(visibility),
          do: {:ok, bookshelf},
          else: {:error, :not_public}
    end
  end

  # Read-path miss-fill: render, attempt to fill the cache, and serve the fresh
  # XML regardless of whether the write succeeds. The cache is an optimization,
  # so a write failure is logged and swallowed rather than surfaced as an error.
  defp render_and_serve(bookshelf) do
    {xml, etag} = render_feed(bookshelf)

    case cache_writer().(bookshelf.id, xml, etag) do
      {:ok, _entry} ->
        :ok

      {:error, changeset} ->
        Logger.warning(
          "Feeds: feed_cache write failed for bookshelf=#{bookshelf.id}, serving fresh render: " <>
            inspect(changeset.errors)
        )
    end

    {:ok, xml, etag}
  end

  defp render_feed(bookshelf) do
    placements = Shelving.get_bookshelf_books(bookshelf.user_id, bookshelf.name)
    xml = build_atom_xml(bookshelf, placements, moved_book_ids(bookshelf, placements))
    etag = compute_etag(xml)
    {xml, etag}
  end

  # Books that *arrived* on this bookshelf from another one.
  #
  # US-6.1 asks for entries reading "Erin moved The Secret History to Library" **or**
  # "Erin added Piranesi to the Reading Pile" — two verbs. Every entry used to say
  # "added", so a move (the more interesting signal, and the one a follower actually
  # wants) was reported as an acquisition.
  #
  # One query for the whole feed rather than one per entry: a shelf can hold hundreds
  # of books and a feed is regenerated on every placement event.
  #
  # Returns a **map** used as a set, not a MapSet and not a list.
  #
  # Not a MapSet: under OTP 28 dialyzer reports `call_without_opaque` when a MapSet
  # built from `Repo.all`'s `any()` result crosses a function boundary — the same issue
  # behind `book_ids_with_user_writing` (b76fa3f3). MapSet is opaque, so dialyzer cannot
  # see through it to the term it was built from.
  #
  # Not a list either, which was the first fix and the wrong one: a list turns the entry
  # loop into O(entries × moved), and this runs on **every placement event**, so a shelf
  # of several hundred mostly-moved books would do six figures of binary comparisons per
  # regeneration. A plain map is O(log n) per lookup, is not opaque, and needs no
  # dialyzer accommodation — the right structure rather than one chosen to satisfy a
  # tool.
  @spec moved_book_ids(map(), list()) :: %{optional(binary()) => true}
  defp moved_book_ids(_bookshelf, []), do: %{}

  defp moved_book_ids(bookshelf, placements) do
    book_ids = Enum.map(placements, & &1.book_id)

    Repo.all(
      from h in PlacementHistory,
        where:
          h.book_id in ^book_ids and h.to_bookshelf == ^bookshelf.id and
            not is_nil(h.from_bookshelf),
        select: h.book_id,
        distinct: true
    )
    |> Map.new(&{&1, true})
  end

  # The cache writer is injectable (defaulting to `put_cache/3`) so tests can
  # force a write failure deterministically — mirrors the `:*_client` seams
  # used elsewhere in the core app.
  defp cache_writer do
    Application.get_env(:core, :feed_cache_writer, &put_cache/3)
  end

  defp build_atom_xml(bookshelf, placements, moved_ids) do
    display_name = feed_display_name(bookshelf.user)

    updated =
      placements
      |> Enum.map(& &1.placed_at)
      |> Enum.reject(&is_nil/1)
      |> Enum.max(DateTime, fn -> DateTime.utc_now() end)
      |> DateTime.to_iso8601()

    entries = Enum.map_join(placements, "\n", &build_entry(&1, bookshelf.name, moved_ids))

    """
    <?xml version="1.0" encoding="utf-8"?>
    <feed xmlns="#{@atom_ns}">
      <title>#{escape_xml(display_name)}'s #{humanize_bookshelf(bookshelf.name)}</title>
      <id>urn:stacks:feed:#{bookshelf.id}</id>
      <updated>#{updated}</updated>
      <author>
        <name>#{escape_xml(display_name)}</name>
      </author>
    #{entries}
    </feed>
    """
    |> String.trim()
  end

  defp build_entry(placement, bookshelf_name, moved_ids) do
    book = placement.book
    title = if book, do: book.title, else: "Unknown Book"

    author_name =
      if book && book.author,
        do: book.author.name,
        else: "Unknown Author"

    isbn = primary_isbn(book)

    placed_at =
      if placement.placed_at,
        do: DateTime.to_iso8601(placement.placed_at),
        else: DateTime.to_iso8601(DateTime.utc_now())

    verb = if Map.has_key?(moved_ids, placement.book_id), do: "moved", else: "added"

    summary =
      "#{escape_xml(title)} by #{escape_xml(author_name)} #{verb} to " <>
        "#{humanize_bookshelf(bookshelf_name)}"

    """
      <entry>
        <title>#{escape_xml(title)}</title>
        <id>urn:stacks:placement:#{placement.id}</id>
        <updated>#{placed_at}</updated>
        <summary>#{summary}</summary>
        <author>
          <name>#{escape_xml(author_name)}</name>
        </author>#{cover_link(placement.book)}#{isbn_link(isbn)}
      </entry>\
    """
  end

  # The cover, as an Atom enclosure.
  #
  # US-6.1 asks each entry to carry a cover thumbnail, and it is what makes a feed
  # browsable in a reader rather than a list of sentences. Taken from the primary
  # edition where there is one, since that is the edition the shelf displays.
  defp cover_link(nil), do: ""

  defp cover_link(book) do
    book
    |> primary_cover_url()
    |> case do
      nil ->
        ""

      url ->
        "\n    <link rel=\"enclosure\" type=\"image/jpeg\" href=\"#{escape_xml(url)}\" />"
    end
  end

  defp primary_cover_url(%{editions: editions}) when is_list(editions) do
    primary = Enum.find(editions, & &1.is_primary) || List.first(editions)
    primary && primary.cover_image_url
  end

  defp primary_cover_url(_book), do: nil

  defp primary_isbn(nil), do: nil

  defp primary_isbn(book) do
    case book.editions do
      editions when is_list(editions) ->
        primary = Enum.find(editions, &(&1.is_primary == true))
        if primary, do: primary.isbn, else: nil

      _ ->
        nil
    end
  end

  defp isbn_link(nil), do: ""

  defp isbn_link(isbn) do
    "\n    <link rel=\"related\" href=\"https://openlibrary.org/isbn/#{isbn}\" />"
  end

  # The public-facing name shown in a feed's <title> and <author>. A feed is a
  # crawlable public artifact, so it must NEVER contain the owner's email (GDPR
  # personal data, #283). Fallback ladder: chosen display_name → claimed handle
  # (always present — op.users.handle is NOT NULL and app-assigned on every
  # insert) → a neutral label as a defensive backstop for a blank handle. Blank
  # strings are treated as absent so an empty value never renders as the name.
  defp feed_display_name(user) do
    cond do
      present?(user.display_name) -> user.display_name
      present?(user.handle) -> user.handle
      true -> "A Stacks reader"
    end
  end

  defp present?(nil), do: false
  defp present?(value) when is_binary(value), do: String.trim(value) != ""

  defp humanize_bookshelf(name) do
    name
    |> String.replace("_", " ")
    |> String.split(" ")
    |> Enum.map_join(" ", &String.capitalize/1)
  end

  defp escape_xml(nil), do: ""

  defp escape_xml(text) do
    text
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
    |> String.replace("'", "&apos;")
  end
end
